/** 物品目录的前端契约；请求由统一 api 客户端发送。 */
import api from '@/api';
import type { FanxiuGongfaLinkedItem, FanxiuGongfaProgressionRow } from './gongfa';
import type { FanxiuFacetIndex, FanxiuTimelineHint } from './catalogCommon';


export interface FanxiuItemStats {
  item_count?: number;
  quality_count?: number;
  progression_linked_item_count?: number;
  activity_count?: number;
  item_with_time_hint_count?: number;
  item_with_effect_detail_count?: number;
  item_with_optional_gift_detail_count?: number;
  item_with_talisman_detail_count?: number;
  item_with_spiritual_body_detail_count?: number;
  item_with_title_detail_count?: number;
  item_with_title_local_detail_count?: number;
  item_with_fashion_detail_count?: number;
  item_with_gongfa_detail_count?: number;
  item_with_gongfa_jie_book_detail_count?: number;
  item_with_gongfa_feature_probe_detail_count?: number;
  item_with_gongfa_local_description_detail_count?: number;
  item_with_physical_exercise_detail_count?: number;
  item_with_partner_detail_count?: number;
  item_with_npc_gift_detail_count?: number;
  item_with_hidden_world_detail_count?: number;
  item_with_pet_gift_detail_count?: number;
  item_with_member_detail_count?: number;
  item_with_member_equipment_detail_count?: number;
  item_with_show_effect_detail_count?: number;
  item_with_take_medicine_detail_count?: number;
  item_with_medical_recipe_detail_count?: number;
  item_with_wallet_resource_detail_count?: number;
  item_with_boss_kill_effect_detail_count?: number;
  item_with_prefixed_effect_detail_count?: number;
  item_with_faze_detail_count?: number;
  item_with_spiritware_detail_count?: number;
  item_with_spiritware_part_detail_count?: number;
  item_with_spiritware_soul_detail_count?: number;
  item_with_spiritware_cleanse_detail_count?: number;
  item_with_spiritware_ultra_material_detail_count?: number;
  item_with_talisman_refine_material_detail_count?: number;
  item_with_swordsoul_detail_count?: number;
  item_with_sword_base_detail_count?: number;
  item_with_flame_square_detail_count?: number;
  item_with_equipment_detail_count?: number;
  item_with_equipment_material_effect_detail_count?: number;
  item_with_coreware_detail_count?: number;
  item_with_partner_weapon_stone_detail_count?: number;
  item_with_redbag_detail_count?: number;
  talisman_detail_count?: number;
  spiritual_body_detail_count?: number;
  title_detail_count?: number;
  title_item_link_count?: number;
  fashion_detail_count?: number;
  gongfa_detail_count?: number;
  gongfa_jie_book_detail_count?: number;
  gongfa_jie_book_jie_row_count?: number;
  gongfa_jie_book_skill_row_count?: number;
  gongfa_feature_probe_detail_count?: number;
  gongfa_feature_probe_family_row_count?: number;
  gongfa_feature_probe_link_row_count?: number;
  physical_exercise_detail_count?: number;
  partner_detail_count?: number;
  npc_gift_detail_count?: number;
  npc_gift_activity_detail_count?: number;
  partner_gift_target_detail_count?: number;
  npc_row_count?: number;
  npc_gift_row_count?: number;
  hidden_world_detail_count?: number;
  hidden_world_item_row_count?: number;
  hidden_world_skill_row_count?: number;
  pet_gift_detail_count?: number;
  pet_gift_row_count?: number;
  member_detail_count?: number;
  member_equipment_detail_count?: number;
  take_medicine_detail_count?: number;
  medical_detail_count?: number;
  wallet_resource_detail_count?: number;
  boss_kill_effect_detail_count?: number;
  boss_kill_effect_row_count?: number;
  faze_detail_count?: number;
  spiritware_detail_count?: number;
  spiritware_part_detail_count?: number;
  spiritware_soul_detail_count?: number;
  spiritware_cleanse_item_detail_count?: number;
  spiritware_cleanse_material_detail_count?: number;
  spiritware_ultra_material_detail_count?: number;
  spiritware_item_row_count?: number;
  spiritware_base_row_count?: number;
  spiritware_ultra_row_count?: number;
  spiritware_soul_row_count?: number;
  spiritware_cleanse_item_row_count?: number;
  swordsoul_base_row_count?: number;
  swordsoul_awakening_row_count?: number;
  swordsoul_lines_row_count?: number;
  swordsoul_awakening_detail_count?: number;
  swordsoul_awakening_empty_cost_row_count?: number;
  swordsoul_line_base_row_count?: number;
  swordsoul_line_level_row_count?: number;
  swordsoul_line_attr_row_count?: number;
  swordsoul_line_attr_quality_row_count?: number;
  swordsoul_eff_row_count?: number;
  swordsoul_line_wash_row_count?: number;
  swordsoul_line_detail_count?: number;
  swordsoul_line_wash_detail_count?: number;
  special_gongfa_jie_row_count?: number;
  special_gongfa_skill_row_count?: number;
  special_gongfa_jie_detail_count?: number;
  sword_base_row_count?: number;
  sword_level_up_row_count?: number;
  sword_key_point_row_count?: number;
  sword_base_detail_count?: number;
  flame_level_row_count?: number;
  flame_square_build_row_count?: number;
  flame_square_level_row_count?: number;
  flame_square_detail_count?: number;
  equipment_item_row_count?: number;
  equipment_gem_row_count?: number;
  equipment_gem_suit_row_count?: number;
  equipment_item_detail_count?: number;
  equipment_gem_detail_count?: number;
  equipment_detail_count?: number;
  core_base_row_count?: number;
  core_map_row_count?: number;
  coreware_base_row_count?: number;
  coreware_level_row_count?: number;
  coreware_detail_count?: number;
  partner_weapon_stone_base_row_count?: number;
  partner_weapon_stone_level_row_count?: number;
  partner_weapon_stone_upgrade_row_count?: number;
  partner_weapon_base_row_count?: number;
  partner_weapon_stone_combination_row_count?: number;
  partner_weapon_stone_detail_count?: number;
  redbag_row_count?: number;
  redbag_detail_count?: number;
  type_count?: number;
  sub_type_count?: number;
  progression_table_counts?: Record<string, number>;
}

export interface FanxiuItemEffectDetail {
  kind?: string;
  title?: string;
  subtitle?: string;
  description?: string;
  plain_description?: string;
  source?: string;
  source_id?: string | number;
  grade_id?: string | number;
  stage?: string | number;
  stage_name?: string;
  quality_name?: string;
  type_label?: string;
  tips?: string;
  attr_text?: string;
  condition?: string;
  model_text?: string;
  level_group?: string | number;
  gongfa_exp?: string | number;
  gongfa_jie_effect_id?: string | number;
  gongfa_jie_gid?: string | number;
  gongfa_jie_name?: string;
  gongfa_jie_skill_name?: string;
  gongfa_jie_count?: string | number;
  gongfa_skill_stage_count?: string | number;
  gongfa_feature_gid?: string | number;
  gongfa_feature_status?: string;
  gongfa_feature_prefixes?: Array<string | number>;
  gongfa_feature_ids?: Array<string | number>;
  gongfa_feature_count?: string | number;
  gongfa_feature_source_jie?: Array<string | number>;
  gongfa_feature_source_names?: Array<string | number>;
  gongfa_feature_candidate_count?: string | number;
  gongfa_feature_candidate_ids?: Array<string | number>;
  gongfa_feature_linked_item_ids?: Array<string | number>;
  feature_stage_text?: string;
  feature_asset_text?: string;
  feature_links?: Array<Record<string, string | number>>;
  gongfa_local_effect_id?: string | number;
  gongfa_local_terms?: Array<string | number>;
  gongfa_local_personality?: string;
  stage_text?: string;
  consume_text?: string;
  medicine_id?: string | number;
  medicine_type?: string;
  max_times_text?: string;
  cooldown_text?: string;
  activity_name?: string;
  effect_type_label?: string;
  max_number?: string | number;
  equipment_group_id?: string | number;
  level_count?: string | number;
  skill_id?: string | number;
  side_skill_ids?: Array<string | number>;
  skill_text?: string;
  medical_id?: string | number;
  recipe_item_id?: string | number;
  product_item_id?: string | number;
  product_item_name?: string;
  material_text?: string;
  waiting_time_text?: string;
  proficiency?: string | number;
  medical_limit?: string | number;
  wallet_resource_id?: string | number;
  wallet_alias?: string;
  boss_kill_effect_id?: string | number;
  effect_type?: string | number;
  max_value?: string | number;
  param?: string | number;
  effect_prefix?: string;
  effect_payload?: string;
  building_id?: string | number;
  building_effect_type?: string | number;
  building_effect_value?: string | number;
  rate_basis_points?: string | number;
  resource_type?: string | number;
  resource_item_id?: string | number;
  activity_id?: string | number;
  resource_id?: string | number;
  duration_seconds?: string | number;
  effect_rule?: string;
  optional_gift_group_id?: string | number;
  optional_gift_reward_count?: string | number;
  optional_gift_reward_text?: string;
  spiritware_item_id?: string | number;
  spiritware_type?: string | number;
  spiritware_name?: string;
  spiritware_part?: string | number;
  spiritware_quality?: string | number;
  spiritware_quality_name?: string;
  spiritware_base_attr_text?: string;
  spiritware_max_attr_text?: string;
  spiritware_cleanse_item_text?: string;
  spiritware_ultra_text?: string;
  spiritware_target_part_text?: string;
  spiritware_ultra_material_text?: string;
  spiritware_soul_grade_count?: string | number;
  spiritware_skill_ids?: string;
  spiritware_cleanse_type?: string | number;
  spiritware_cleanse_type_label?: string;
  spiritware_cleanse_limit_type?: string | number;
  spiritware_cleanse_part_count?: string | number;
  linked_talisman_id?: string | number;
  target_talisman_id?: string | number;
  target_talisman_name?: string;
  target_talisman_text_name?: string;
  swordsoul_item_id?: string | number;
  swordsoul_id?: string | number;
  swordsoul_name?: string;
  swordsoul_part?: string | number;
  swordsoul_part_name?: string;
  swordsoul_stage_count?: string | number;
  swordsoul_awaken_text?: string;
  swordsoul_unlock_text?: string;
  swordsoul_open_condition?: string;
  swordsoul_show_condition?: string;
  swordsoul_line_item_id?: string | number;
  swordsoul_line_quality?: string | number;
  swordsoul_line_quality_name?: string;
  swordsoul_line_entry_num?: string | number;
  swordsoul_line_attr_group?: string | number;
  swordsoul_line_attr_text?: string;
  swordsoul_line_level_group?: string | number;
  swordsoul_line_max_level?: string | number;
  swordsoul_line_level_text?: string;
  swordsoul_line_level_cost_text?: string;
  swordsoul_line_effect_text?: string;
  swordsoul_line_breakdown_text?: string;
  swordsoul_line_breakdown_per_level_text?: string;
  swordsoul_line_wash_item_id?: string | number;
  swordsoul_line_wash_target_souls?: Array<string | number>;
  swordsoul_line_wash_target_parts?: Array<string | number>;
  special_gongfa_item_id?: string | number;
  special_gongfa_gid?: string | number;
  special_gongfa_jie?: string | number;
  special_gongfa_pin?: string | number;
  special_gongfa_skill_group?: string | number;
  special_gongfa_skill_name?: string;
  special_gongfa_skill_text?: string;
  special_gongfa_cd_text?: string;
  special_gongfa_origin_text?: string;
  special_gongfa_attr_text?: string;
  special_gongfa_max_attr_text?: string;
  title_effect_value?: string | number;
  sword_item_id?: string | number;
  sword_id?: string | number;
  sword_name?: string;
  sword_model?: string | number;
  sword_effect_asset?: string;
  sword_local_target_name?: string;
  sword_cost_text?: string;
  sword_show_condition?: string;
  sword_level_count?: string | number;
  sword_initial_text?: string;
  sword_final_text?: string;
  sword_key_point_count?: string | number;
  sword_key_point_text?: string;
  sword_initial_faze_id?: string | number;
  sword_final_faze_id?: string | number;
  flame_item_id?: string | number;
  flame_id?: string | number;
  flame_name?: string;
  flame_level_count?: string | number;
  flame_condition_text?: string;
  flame_cost_text?: string;
  flame_initial_attr_text?: string;
  flame_final_attr_text?: string;
  flame_square_text?: string;
  equipment_item_id?: string | number;
  equipment_type?: string | number;
  equipment_type_name?: string;
  equipment_suit_title?: string;
  equipment_attr_text?: string;
  equipment_fixed_tag_text?: string;
  equipment_affix_text?: string;
  equipment_level_group?: string | number;
  equipment_star_group?: string | number;
  equipment_gem_item_id?: string | number;
  equipment_special_gem_item_id?: string | number;
  equipment_material_item_id?: string | number;
  equipment_material_effect_id?: string | number;
  equipment_material_effect_title?: string;
  gem_item_id?: string | number;
  gem_type?: string | number;
  gem_level?: string | number;
  gem_score?: string | number;
  gem_attr_text?: string;
  gem_location_text?: string;
  gem_suit_title?: string;
  gem_suit_text?: string;
  gem_skill_id?: string | number;
  gem_skill_text?: string;
  coreware_item_id?: string | number;
  coreware_type?: string | number;
  coreware_type_name?: string;
  coreware_part?: string | number;
  coreware_part_name?: string;
  coreware_quality?: string | number;
  coreware_quality_name?: string;
  coreware_main_attr?: string;
  coreware_main_attr_name?: string;
  coreware_initial_attr_text?: string;
  coreware_max_attr_text?: string;
  coreware_level_text?: string;
  coreware_level_count?: string | number;
  coreware_total_exp?: string | number;
  coreware_element_num_limit?: string | number;
  coreware_unlock_element_levels?: Array<string | number>;
  coreware_random_side_attr_levels?: Array<string | number>;
  coreware_exp?: string | number;
  coreware_exp_off?: string | number;
  coreware_condition_text?: string;
  partner_weapon_stone_item_id?: string | number;
  partner_weapon_stone_type?: string | number;
  partner_weapon_stone_type_name?: string;
  partner_weapon_partner_id?: string | number;
  partner_weapon_partner_name?: string;
  partner_weapon_id?: string | number;
  partner_weapon_name?: string;
  partner_weapon_stone_quality?: string | number;
  partner_weapon_stone_quality_name?: string;
  partner_weapon_stone_default_exp?: string | number;
  partner_weapon_stone_level_text?: string;
  partner_weapon_stone_initial_attr_text?: string;
  partner_weapon_stone_max_attr_text?: string;
  partner_weapon_stone_upgrade_text?: string;
  partner_weapon_stone_upgrade_consume_text?: string;
  partner_weapon_stone_upgrade_initial_attr_text?: string;
  partner_weapon_stone_upgrade_max_attr_text?: string;
  partner_weapon_stone_combination_text?: string;
  redbag_id?: string | number;
  redbag_name?: string;
  redbag_quantity?: string | number;
  redbag_daily_num?: string | number;
  redbag_condition_text?: string;
  redbag_event_text?: string;
  redbag_reward_item_id?: string | number;
  redbag_reward_item_name?: string;
  redbag_reward_text?: string;
  redbag_tier_text?: string;
  redbag_tiers?: Array<{
    weight?: string | number;
    percent?: string;
    range_min?: string | number;
    range_max?: string | number;
    range_text?: string;
    token?: string;
  }>;
  npc_id?: string | number;
  npc_name?: string;
  npc_gift_item_ids?: Array<string | number>;
  npc_gift_item_names?: string[];
  target_partner_ids?: Array<string | number>;
  target_partner_names?: string[];
  target_partner_unknown_ids?: Array<string | number>;
  hidden_world_item_id?: string | number;
  hidden_world_item_type?: string | number;
  hidden_world_item_type_label?: string;
  skill_ids?: Array<string | number>;
  skill_names?: string[];
  pet_gift_id?: string | number;
  pet_gift_rate?: string | number;
  attr_entries?: Array<{ key?: string; label?: string; value?: string | number }>;
  max_attr_entries?: Array<{ key?: string; label?: string; value?: string | number }>;
  wear_attr_entries?: Array<{ key?: string; label?: string; value?: string | number }>;
}

export interface FanxiuItemCard {
  id: string | number;
  name: string;
  quality?: string | number;
  quality_name?: string;
  quality_color?: string;
  quality_tab?: string;
  icon?: string;
  small_icon?: string;
  description?: string;
  effect_description?: string;
  effect_detail_preview?: string;
  show_effect?: string;
  type?: string | number;
  type_key?: string;
  type_name?: string;
  sub_type?: string | number;
  sub_type_key?: string;
  sub_type_raw_key?: string;
  sub_type_name?: string;
  type_sub_type_name?: string;
  overlay?: string | number;
  backpack?: string | number;
  effect_value?: unknown;
  stone_value?: string | number;
  can_use?: string | number | boolean;
  sort?: string | number;
  progression_counts?: Record<string, number>;
  progression?: Record<string, FanxiuGongfaProgressionRow[]>;
  optional_gift_group_id?: string | number;
  optional_gift_rewards?: FanxiuGongfaLinkedItem[];
  linked_talisman_id?: string | number;
  linked_spiritual_body_id?: string | number;
  linked_title_id?: string | number;
  linked_fashion_id?: string | number;
  linked_gongfa_id?: string | number;
  linked_gongfa_jie_effect_id?: string | number;
  linked_gongfa_jie_gid?: string | number;
  linked_gongfa_feature_gid?: string | number;
  linked_gongfa_feature_prefixes?: Array<string | number>;
  linked_special_gongfa_item_id?: string | number;
  linked_special_gongfa_gid?: string | number;
  linked_physical_exercise_id?: string | number;
  linked_partner_id?: string | number;
  linked_hidden_world_item_id?: string | number;
  linked_pet_gift_id?: string | number;
  linked_member_id?: string | number;
  linked_member_equipment_group_id?: string | number;
  linked_member_equipment_item_id?: string | number;
  linked_medical_id?: string | number;
  linked_wallet_resource_id?: string | number;
  linked_boss_kill_effect_id?: string | number;
  linked_faze_id?: string | number;
  linked_spiritware_item_id?: string | number;
  linked_talisman_refine_target_id?: string | number;
  linked_swordsoul_item_id?: string | number;
  linked_swordsoul_line_item_id?: string | number;
  linked_swordsoul_id?: string | number;
  linked_swordsoul_part?: string | number;
  linked_sword_item_id?: string | number;
  linked_sword_id?: string | number;
  linked_flame_item_id?: string | number;
  linked_flame_id?: string | number;
  linked_equipment_item_id?: string | number;
  linked_equipment_gem_item_id?: string | number;
  linked_equipment_material_effect_id?: string | number;
  linked_coreware_item_id?: string | number;
  linked_partner_weapon_stone_item_id?: string | number;
  linked_partner_weapon_partner_id?: string | number;
  linked_partner_weapon_id?: string | number;
  linked_redbag_id?: string | number;
  effect_details?: FanxiuItemEffectDetail[];
  time_hints?: FanxiuTimelineHint[];
  first_time_hint?: FanxiuTimelineHint | null;
  source_table?: string;
  source_path?: string;
  source_row_key?: string | number;
  icon_source_table?: string;
  icon_source_field?: string;
  icon_reuse_count?: number;
  icon_quality_risk?: string;
  icon_quality_note?: string;
  small_icon_reuse_count?: number;
  small_icon_quality_risk?: string;
  small_icon_quality_note?: string;
  terms?: string[];
}

export interface FanxiuItemSearchItem {
  id: string | number;
  name: string;
  quality?: string | number;
  quality_name?: string;
  quality_color?: string;
  quality_tab?: string;
  icon?: string;
  small_icon?: string;
  type?: string | number;
  type_key?: string;
  type_name?: string;
  sub_type?: string | number;
  sub_type_key?: string;
  sub_type_raw_key?: string;
  sub_type_name?: string;
  type_sub_type_name?: string;
  description_preview?: string;
  effect_preview?: string;
  effect_detail_preview?: string;
  progression_counts?: Record<string, number>;
  first_time_hint?: FanxiuTimelineHint | null;
  source_table?: string;
  source_path?: string;
  source_row_key?: string | number;
  icon_source_table?: string;
  icon_source_field?: string;
  icon_reuse_count?: number;
  icon_quality_risk?: string;
  icon_quality_note?: string;
  small_icon_reuse_count?: number;
  small_icon_quality_risk?: string;
  small_icon_quality_note?: string;
  terms: string[];
  score: number;
}

export interface FanxiuItemQualityOption {
  value: string;
  label: string;
  count: number;
  quality?: string | number;
  quality_color?: string;
  quality_tab?: string;
}

export interface FanxiuItemTypeOption {
  value: string;
  label: string;
  count: number;
  type?: string | number;
  type_key?: string;
  type_name?: string;
  sub_type?: string | number;
  sub_type_raw_key?: string;
  sub_type_name?: string;
}

export interface FanxiuItemIconQualityOption {
  value: string;
  label: string;
  count: number;
}

export interface FanxiuItemIconOption {
  value: string;
  label: string;
  count: number;
  type_summary?: string;
  dominant_type?: string;
  dominant_type_ratio?: number;
  review_hint?: string;
  review_priority?: string;
  samples?: Array<{
    id?: string | number;
    name?: string;
    resource_type?: string;
    resource_href?: string;
    type_name?: string;
  }>;
}

export interface FanxiuItemIconQualityReviewRow {
  field: string;
  icon: string;
  risk?: string;
  count: string | number;
  threshold?: string | number;
  review_priority?: string;
  review_hint?: string;
  recommended_action?: string;
  dominant_type?: string;
  dominant_type_count?: string | number;
  dominant_type_ratio?: string | number;
  type_count?: string | number;
  type_summary?: string;
  sub_type_count?: string | number;
  sub_type_summary?: string;
  quality_summary?: string;
  source_summary?: string;
  name_prefix_count?: string | number;
  name_prefix_summary?: string;
  companion_field?: string;
  companion_icon_count?: string | number;
  companion_icon_summary?: string;
  samples?: string;
  samples_json?: string;
  candidate_icon_count?: string | number;
  candidate_icons_json?: string;
  nearby_icon_count?: string | number;
  nearby_icons_json?: string;
  representative_samples?: Array<{
    id?: string | number;
    name?: string;
    type_name?: string;
    sub_type_name?: string;
    type_sub_type_name?: string;
    quality_name?: string;
    icon?: string;
    small_icon?: string;
  }>;
  candidate_icons?: Array<{
    icon?: string;
    score?: string | number;
    reason?: string;
  }>;
  nearby_icons?: Array<{
    icon?: string;
    number_delta?: string | number;
    reason?: string;
  }>;
}

export interface FanxiuItemIconQualityReviewSummary {
  catalog_path?: string;
  output_dir?: string;
  threshold?: number;
  item_count?: number;
  group_count?: number;
  primary_group_count?: number;
  small_group_count?: number;
  high_priority_count?: number;
  medium_priority_count?: number;
  low_priority_count?: number;
  candidate_group_count?: number;
  candidate_icon_total?: number;
  no_candidate_group_count?: number;
  unresolved_no_candidate_group_count?: number;
  no_candidate_review_status?: string;
  nearby_context_group_count?: number;
  nearby_context_icon_total?: number;
  no_candidate_contact_sheet_path?: string;
  no_candidate_groups?: Array<{
    field?: string;
    icon?: string;
    count?: number;
    review_priority?: string;
    review_hint?: string;
    type_summary?: string;
    review_status?: string;
    suggested_manual_action?: string;
    recommended_action?: string;
    remaining_risk?: string;
    sample?: {
      id?: string | number;
      name?: string;
      resource_type?: string;
      resource_href?: string;
      type_name?: string;
      sub_type_name?: string;
      type_sub_type_name?: string;
      quality_name?: string;
      icon?: string;
      small_icon?: string;
    };
    nearby_icon_count?: number;
    nearby_icons?: Array<{
      icon?: string;
      number_delta?: string | number;
      reason?: string;
    }>;
  }>;
  top_groups?: Array<{
    field?: string;
    icon?: string;
    count?: number;
    review_priority?: string;
    review_hint?: string;
    type_summary?: string;
    candidate_icon_count?: number;
    nearby_icon_count?: number;
  }>;
}

export interface FanxiuItemIconQualityReviewResponse {
  summary: FanxiuItemIconQualityReviewSummary;
  items: FanxiuItemIconQualityReviewRow[];
  total: number;
  output_dir?: string;
}

export interface FanxiuItemSearchResponse {
  query: string;
  quality_name?: string;
  type_key?: string;
  sub_type_key?: string;
  icon_quality?: string;
  icon_name?: string;
  small_icon_quality?: string;
  small_icon_name?: string;
  sort_by?: string;
  sort_order?: string;
  limit: number;
  offset: number;
  total: number;
  stats: FanxiuItemStats;
  catalog_path: string;
  quality_options?: FanxiuItemQualityOption[];
  type_options?: FanxiuItemTypeOption[];
  sub_type_options?: FanxiuItemTypeOption[];
  icon_quality_options?: FanxiuItemIconQualityOption[];
  high_reuse_icon_options?: FanxiuItemIconOption[];
  small_icon_quality_options?: FanxiuItemIconQualityOption[];
  high_reuse_small_icon_options?: FanxiuItemIconOption[];
  facet_index?: FanxiuFacetIndex;
  items: FanxiuItemSearchItem[];
}

export interface FanxiuItemCardResponse {
  catalog_path: string;
  card: FanxiuItemCard;
}

export interface FanxiuItemCardsByIdsResponse {
  catalog_path: string;
  cards: FanxiuItemCard[];
  missing: string[];
}

export const searchFanxiuItemCards = (params: {
  query?: string;
  quality_name?: string;
  type_key?: string;
  sub_type_key?: string;
  icon_quality?: string;
  icon_name?: string;
  small_icon_quality?: string;
  small_icon_name?: string;
  sort_by?: string;
  sort_order?: string;
  limit?: number;
  offset?: number;
  include_facets?: boolean;
} = {}) => {
  return api.get<FanxiuItemSearchResponse>('/fanxiu/resources/items/cards', { params }).then(res => res.data);
};

export const getFanxiuItemCard = (itemId: string | number) => {
  return api
    .get<FanxiuItemCardResponse>('/fanxiu/resources/items/card', { params: { item_id: itemId } })
    .then(res => res.data);
};

export const getFanxiuItemCardsByIds = (itemIds: Array<string | number>) => {
  return api
    .get<FanxiuItemCardsByIdsResponse>('/fanxiu/resources/items/cards/by-ids', {
      params: { item_ids: itemIds.join(',') },
    })
    .then(res => res.data);
};

export const getFanxiuItemIconQualityReview = () => {
  return api
    .get<FanxiuItemIconQualityReviewResponse>('/fanxiu/resources/items/icon-quality-review')
    .then(res => res.data);
};
