"""Compatibility bridge for shared WJX automation helpers."""

from pyxllib.ext.wjxlib import (
    DEFAULT_COURSE_QUESTION_TITLE,
    WjxAutomationError,
    WjxSession,
    apply_course_changes,
    apply_template_changes,
    clean_wjx_popups,
    create_wjx_session,
    ensure_logged_in,
    enter_course_question_edit_mode,
    execute_wjx_template_action,
    finish_editing,
    inspect_template,
    open_design_page,
    open_edit_page,
    pause_responses,
    read_course_options,
    resolve_wjx_credentials,
    resume_responses,
)

__all__ = [
    "DEFAULT_COURSE_QUESTION_TITLE",
    "WjxAutomationError",
    "WjxSession",
    "apply_course_changes",
    "apply_template_changes",
    "clean_wjx_popups",
    "create_wjx_session",
    "ensure_logged_in",
    "enter_course_question_edit_mode",
    "execute_wjx_template_action",
    "finish_editing",
    "inspect_template",
    "open_design_page",
    "open_edit_page",
    "pause_responses",
    "read_course_options",
    "resolve_wjx_credentials",
    "resume_responses",
]
