import sqlite3
import os
import uuid
from backend.core.settings import get_settings
from backend.core.device import get_device_id

def fix_device_id():
    # 1. Get the current (new) device ID generated by the system
    # This might create a new identity file if not exists
    new_device_id = get_device_id()
    print(f"Current System Device ID: {new_device_id}")
    
    # 2. Identify the old device ID
    # We know it from previous steps, but let's verify from DB just in case
    settings = get_settings()
    db_path = settings.database_url.replace("sqlite:///", "")
    print(f"Database: {db_path}")
    
    if not os.path.exists(db_path):
        print("Database not found!")
        return

    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    # Find most common device_id in task table that is NOT the new one
    cursor.execute("SELECT device_id, COUNT(*) as c FROM task GROUP BY device_id ORDER BY c DESC")
    rows = cursor.fetchall()
    
    old_device_id = None
    for row in rows:
        did = row[0]
        count = row[1]
        print(f"Found Device ID in tasks: {did} (count: {count})")
        if did != new_device_id and did != "local":
             # Assuming the one with most tasks is the old one we want to migrate
             if old_device_id is None:
                 old_device_id = did
    
    if not old_device_id:
        # Fallback to hardcoded known old ID if detection fails (e.g. if table only has old ID)
        # In this case, if new_device_id is not in table, rows[0] is old ID.
        if rows:
             old_device_id = rows[0][0]
        else:
             print("No tasks found to migrate.")
             return
    
    # Force override for testing if detection fails
    known_old_id = "c6ed30af-6b81-4ef5-941f-f851073dca2f"
    if known_old_id != new_device_id:
        print(f"Forcing migration from known old ID: {known_old_id}")
        old_device_id = known_old_id

    if old_device_id == new_device_id:
        print("Old and New Device IDs are the same. No migration needed.")
        return

    print(f"Migrating tasks from Old ID: {old_device_id} -> New ID: {new_device_id}")
    
    try:
        # Update Task
        cursor.execute("UPDATE task SET device_id = ? WHERE device_id = ?", (new_device_id, old_device_id))
        print(f"  Updated {cursor.rowcount} tasks.")
        
        # Update TaskRuntime
        try:
            cursor.execute("UPDATE taskruntime SET device_id = ? WHERE device_id = ?", (new_device_id, old_device_id))
            print(f"  Updated {cursor.rowcount} runtime entries.")
        except Exception as e:
            print(f"  Error updating runtime: {e}")

        # Update UserDeviceEntry
        try:
            cursor.execute("UPDATE userdeviceentry SET device_id = ? WHERE device_id = ?", (new_device_id, old_device_id))
            print(f"  Updated {cursor.rowcount} device entries.")
        except Exception as e:
             print(f"  Error updating device entries: {e}")

        conn.commit()
        print("Migration successful.")
        
    except Exception as e:
        print(f"Error during migration: {e}")
        conn.rollback()
    finally:
        conn.close()

if __name__ == "__main__":
    fix_device_id()
