from __future__ import annotations

from typing import Any


def _task_template_fields(task_type: str, label: str, *, source: str = "preset", trigger_kind: str = "") -> dict[str, Any]:
    return {
        "template_id": task_type,
        "template_label": label,
        "template_source": source,
        **({"trigger_kind": trigger_kind} if trigger_kind else {}),
    }


def default_data_annotation_scheduler_tasks() -> list[dict[str, Any]]:
    def manual_task(
        task_id: str,
        task_type: str,
        label: str,
        *,
        interruptible: bool = True,
        dispatch_order: int = 0,
        retry_policy: str = "standard",
        payload: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        return {
            "id": task_id,
            "task_type": task_type,
            "label": label,
            "source": "data_annotation_runtime",
            "schedule_kind": "manual",
            **_task_template_fields(task_type, label, trigger_kind="manual"),
            "legacy_name": "",
            "enabled": False,
            "interruptible": interruptible,
            "dispatch_order": dispatch_order,
            "retry_policy": retry_policy,
            "next_time": None,
            "schedule_times": [],
            "window": None,
            "last_run_at": None,
            "last_result": "",
            "retry_after": None,
            "cooldown_seconds": 0,
            "payload": payload or {},
            "scheduler_meta": None,
        }

    def legacy_dynamic_task(task_id: str, legacy_name: str, *, fallback_minutes: int | None = None) -> dict[str, Any]:
        return {
            "id": task_id,
            "task_type": "legacy_dynamic_task",
            "label": legacy_name.replace("_", " "),
            "source": "legacy_behavior_tree",
            "schedule_kind": "dynamic",
            **_task_template_fields("legacy_dynamic_task", legacy_name.replace("_", " "), trigger_kind="dynamic"),
            "legacy_name": legacy_name,
            "enabled": False,
            "interruptible": True,
            "dispatch_order": 0,
            "retry_policy": "standard",
            "next_time": None,
            "schedule_times": [],
            "window": None,
            "last_run_at": None,
            "last_result": "",
            "retry_after": None,
            "cooldown_seconds": (fallback_minutes or 0) * 60,
            "payload": {"legacy_name": legacy_name, **({"fallback_minutes": fallback_minutes} if fallback_minutes else {})},
            "scheduler_meta": None,
        }

    def legacy_daily_task(
        task_id: str,
        legacy_name: str,
        *schedule_times: str,
        window: tuple[str, str] | None = None,
        args: tuple[Any, ...] = (),
    ) -> dict[str, Any]:
        task_type = "legacy_daily_task"
        payload: dict[str, Any] = {"legacy_name": legacy_name, "args": list(args)}
        return {
            "id": task_id,
            "task_type": task_type,
            "label": legacy_name.replace("_", " "),
            "source": "legacy_behavior_tree",
            "schedule_kind": "daily",
            **_task_template_fields(task_type, legacy_name.replace("_", " "), trigger_kind="daily"),
            "legacy_name": legacy_name,
            "enabled": False,
            "interruptible": True,
            "dispatch_order": 0,
            "retry_policy": "standard",
            "next_time": None,
            "schedule_times": list(schedule_times),
            "window": list(window) if window else None,
            "last_run_at": None,
            "last_result": "",
            "retry_after": None,
            "cooldown_seconds": 0,
            "payload": payload,
            "scheduler_meta": None,
        }

    def runtime_daily_task(
        task_id: str,
        task_type: str,
        label: str,
        *schedule_times: str,
        enabled: bool = True,
        interruptible: bool = True,
        dispatch_order: int = 0,
        retry_policy: str = "standard",
        window: tuple[str, str] | None = None,
        cooldown_seconds: int = 0,
        payload: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        return {
            "id": task_id,
            "task_type": task_type,
            "label": label,
            "source": "data_annotation_runtime",
            "schedule_kind": "daily",
            **_task_template_fields(task_type, label, trigger_kind="daily"),
            "legacy_name": label,
            "enabled": enabled,
            "interruptible": interruptible,
            "dispatch_order": dispatch_order,
            "retry_policy": retry_policy,
            "next_time": None,
            "schedule_times": list(schedule_times),
            "window": list(window) if window else None,
            "last_run_at": None,
            "last_result": "",
            "retry_after": None,
            "cooldown_seconds": cooldown_seconds,
            "payload": payload or {},
            "scheduler_meta": None,
        }

    def runtime_weekly_task(
        task_id: str,
        task_type: str,
        label: str,
        *,
        weekdays: list[int],
        schedule_times: list[str],
        enabled: bool = True,
        interruptible: bool = True,
        dispatch_order: int = 0,
        retry_policy: str = "standard",
        cooldown_seconds: int = 0,
        payload: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        return {
            "id": task_id,
            "task_type": task_type,
            "label": label,
            "source": "data_annotation_runtime",
            "schedule_kind": "weekly",
            **_task_template_fields(task_type, label, trigger_kind="weekly"),
            "legacy_name": label,
            "enabled": enabled,
            "interruptible": interruptible,
            "dispatch_order": dispatch_order,
            "retry_policy": retry_policy,
            "next_time": None,
            "schedule_times": list(schedule_times),
            "weekdays": list(weekdays),
            "window": None,
            "last_run_at": None,
            "last_result": "",
            "retry_after": None,
            "cooldown_seconds": cooldown_seconds,
            "payload": payload or {},
            "scheduler_meta": None,
        }

    def runtime_dynamic_task(
        task_id: str,
        task_type: str,
        label: str,
        *,
        enabled: bool = False,
        interruptible: bool = True,
        dispatch_order: int = 0,
        retry_policy: str = "standard",
        cooldown_seconds: int = 0,
        payload: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        return {
            "id": task_id,
            "task_type": task_type,
            "label": label,
            "source": "data_annotation_runtime",
            "schedule_kind": "dynamic",
            **_task_template_fields(task_type, label, trigger_kind="dynamic"),
            "legacy_name": label,
            "enabled": enabled,
            "interruptible": interruptible,
            "dispatch_order": dispatch_order,
            "retry_policy": retry_policy,
            "next_time": None,
            "schedule_times": [],
            "window": None,
            "last_run_at": None,
            "last_result": "",
            "retry_after": None,
            "cooldown_seconds": cooldown_seconds,
            "payload": payload or {},
            "scheduler_meta": None,
        }

    return [
        {
            "id": "gift-code-weekly",
            "task_type": "gift_code_redeem",
            "label": "每周礼包码",
            "source": "data_annotation_runtime",
            "schedule_kind": "manual",
            **_task_template_fields("gift_code_redeem", "每周礼包码", trigger_kind="manual"),
            "legacy_name": "",
            "enabled": False,
            "interruptible": True,
            "dispatch_order": 0,
            "retry_policy": "standard",
            "next_time": None,
            "schedule_times": [],
            "window": None,
            "last_run_at": None,
            "last_result": "",
            "retry_after": None,
            "cooldown_seconds": 0,
            "payload": {"codes": []},
            "scheduler_meta": None,
        },
        manual_task("go-settings", "go_scene", "到设置页 #49", payload={"target_scene_id": 49}),
        manual_task("hide-floating-window", "hide_floating_window", "隐藏浮动窗"),
        runtime_daily_task(
            "daily-lundao-seat",
            "daily_lundao",
            "论道_座位",
            "15:55",
            retry_policy="immediate",
            window=("15:55", "22:00"),
            cooldown_seconds=300,
        ),
        manual_task("daily-xianyuan-duel", "daily_xianyuan_duel", "仙缘_斗法"),
        runtime_daily_task(
            "daily-daofa",
            "daily_daofa",
            "道法争锋",
            "19:00",
            cooldown_seconds=600,
        ),
        runtime_daily_task(
            "daily-lingmai-seat",
            "daily_lingmai",
            "灵脉_座位",
            "17:30",
            cooldown_seconds=600,
            payload={"lingmai_no_target_retry_seconds": 1800},
        ),
        runtime_daily_task(
            "mail-selective-claim",
            "mail_selective_claim",
            "邮件_选择性领取",
            "00:05",
            cooldown_seconds=600,
            payload={"max_runtime_seconds": 3600},
        ),
        runtime_daily_task("daily-boss", "daily_boss", "日常_首领", "05:00", cooldown_seconds=600, payload={"max_runtime_seconds": 1800}),
        runtime_dynamic_task("xianfu-visit-partner", "xianfu_visit_partner", "仙府_寻访仙侣", enabled=True, cooldown_seconds=600),
        runtime_dynamic_task("xianfu-learn-skill", "xianfu_learn_skill", "仙府_领悟绝技", enabled=True, cooldown_seconds=600),
        legacy_dynamic_task("legacy-dynamic-xianlv-lilian", "日常_仙侣历练", fallback_minutes=60),
        runtime_daily_task(
            "legacy-daily-mozu",
            "daily_mozu",
            "日常_魔祖",
            "12:30",
            window=("12:30", "12:35"),
        ),
        runtime_daily_task(
            "legacy-daily-lingquan",
            "daily_lingquan",
            "日常_灵泉",
            "20:30",
            window=("20:30", "20:43"),
            cooldown_seconds=600,
            payload={"max_runtime_seconds": 1800},
        ),
        runtime_daily_task(
            "daily-zhenxie",
            "daily_zhenxie",
            "日常_镇邪",
            "21:00",
            window=("21:00", "21:05"),
        ),
        runtime_daily_task("legacy-daily-assistant", "daily_assistant", "日常_助手", "00:00", "06:00", "12:00", "18:00", cooldown_seconds=600),
        runtime_daily_task("legacy-daily-signup", "daily_signup", "日常_报名", "05:00", cooldown_seconds=600),
        runtime_daily_task(
            "xianqiao-trial",
            "xianqiao_trial",
            "仙窍_试炼",
            "05:00",
            cooldown_seconds=600,
            payload={
                "target_daily_purchases": 3,
                "max_challenges": 10,
                "battle_timeout": 360,
                "max_runtime_seconds": 3600,
            },
        ),
        runtime_daily_task("legacy-daily-vip", "daily_vip", "日常_vip", "00:00", enabled=True, cooldown_seconds=600),
        legacy_daily_task("legacy-daily-zongmen-redpacket", "日常_宗门红包", "05:00", "12:00", "06:00", "00:00"),
        runtime_daily_task("legacy-daily-dongtian", "daily_dongtian", "洞天_领取", "14:00", window=("10:00", "22:00"), cooldown_seconds=600),
        runtime_daily_task(
            "legacy-daily-dongtian-clear",
            "daily_dongtian_clear",
            "洞天_行动力",
            "21:30",
            window=("10:00", "22:00"),
            cooldown_seconds=600,
            dispatch_order=20,
            retry_policy="immediate",
        ),
        runtime_daily_task(
            "legacy-daily-lingmai-clear",
            "daily_lingmai_clear",
            "灵脉_清体力",
            "21:30",
            window=("10:00", "22:00"),
            cooldown_seconds=600,
            dispatch_order=10,
            retry_policy="immediate",
        ),
        runtime_daily_task(
            "legacy-daily-mojie-raid",
            "daily_mojie_raid",
            "日常_奇袭魔界",
            "13:00",
            "21:30",
            cooldown_seconds=600,
            dispatch_order=30,
        ),
        runtime_daily_task("legacy-daily-baiye", "daily_baiye", "日常_拜谒", "05:00", cooldown_seconds=600, payload={"args": ["魔道"]}),
        runtime_daily_task("legacy-daily-green-bottle-baiye", "daily_green_bottle_baiye", "日常_绿瓶拜谒", "05:00", cooldown_seconds=600),
        runtime_daily_task("legacy-daily-gongfeng", "daily_gongfeng", "日常_供奉", "05:00", cooldown_seconds=600),
        runtime_daily_task("legacy-daily-xianshi", "daily_xianshi", "仙市_秘藏阁", "05:00", cooldown_seconds=600),
        runtime_weekly_task(
            "xianshi-weekly-resources",
            "xianshi_weekly_resources",
            "仙市_每周资源",
            weekdays=[0],
            schedule_times=["00:05", "05:05"],
            enabled=False,
            cooldown_seconds=600,
        ),
        runtime_weekly_task(
            "daily-weekly-dungeon",
            "daily_weekly_dungeon",
            "日常_周本",
            weekdays=[0],
            schedule_times=["05:00"],
            cooldown_seconds=600,
            payload={"battle_return_world_timeout": 600},
        ),
        runtime_dynamic_task("legacy-daily-xianmeng", "daily_xianmeng", "日常_仙盟", enabled=False, cooldown_seconds=600, payload={"max_runtime_seconds": 7200}),
        runtime_daily_task("legacy-daily-xianyuan", "daily_xianyuan", "日常_挑战仙缘", "05:00", cooldown_seconds=600),
        runtime_daily_task(
            "legacy-daily-activity",
            "daily_activity",
            "日常_活跃度",
            "11:00",
            enabled=True,
            cooldown_seconds=3600,
            payload={"fallback_seconds": 3600},
        ),
    ]


