import type { AppPageDefinition } from '@/router/pageRegistryTypes'

export const standardPageRegistry: AppPageDefinition[] = [
  {
    routeName: 'Home',
    canonicalPath: '/',
    component: () => import('./home/page.vue'),
    permissionKey: 'home',
  },
  {
    routeName: 'AuthorContact',
    canonicalPath: '/contact-author',
    component: () => import('./author-contact/page.vue'),
    permissionKey: 'author-contact',
  },
  {
    routeName: 'FanxiuWiki',
    canonicalPath: '/fanxiu/wiki',
    component: () => import('./fanxiu/wiki/page.vue'),
  },
  {
    routeName: 'FanxiuDataAnnotation',
    canonicalPath: '/fanxiu/data-annotation',
    component: () => import('./fanxiu/data-annotation/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'FanxiuKernelScheduler',
    canonicalPath: '/fanxiu/kernel-scheduler',
    component: () => import('./fanxiu/kernel-scheduler/page.vue'),
    permissionKey: 'fanxiu.kernel-scheduler',
    menuPath: '/fanxiu/kernel-scheduler',
    requiresAuth: true,
  },
  {
    routeName: 'FanxiuKernelSchedulerLogs',
    canonicalPath: '/fanxiu/kernel-scheduler/logs',
    component: () => import('./fanxiu/kernel-scheduler-logs/page.vue'),
    permissionKey: 'fanxiu.kernel-scheduler',
    menuPath: null,
    requiresAuth: true,
  },
  {
    routeName: 'FanxiuActivityList',
    canonicalPath: '/fanxiu/activity-list',
    component: () => import('./fanxiu/activity-list/page.vue'),
  },
  {
    routeName: 'FanxiuKunlunSecret',
    canonicalPath: '/fanxiu/activity-list/kunlun-secret',
    component: () => import('./fanxiu/kunlun-secret/page.vue'),
  },
  {
    routeName: 'FanxiuSchedule',
    canonicalPath: '/fanxiu/schedule',
    component: () => import('./fanxiu/schedule/page.vue'),
  },
  {
    routeName: 'FanxiuDivineResource',
    canonicalPath: '/fanxiu/activity-list/divine-resource',
    component: () => import('./fanxiu/divine-resource/page.vue'),
  },
  {
    routeName: 'FanxiuQijiZhumo',
    canonicalPath: '/fanxiu/activity-list/qiji-zhumo',
    component: () => import('./fanxiu/qiji-zhumo/page.vue'),
  },
  {
    routeName: 'FanxiuLabelmeBrowser',
    canonicalPath: '/fanxiu/labelme',
    component: () => import('./fanxiu/labelme/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'FanxiuWardrobeHall',
    canonicalPath: '/fanxiu/inventory/wardrobe-hall',
    component: () => import('./fanxiu/wardrobe-hall/page.vue'),
  },
  {
    routeName: 'FanxiuSpiritBeastHall',
    canonicalPath: '/fanxiu/inventory/spirit-beast-hall',
    component: () => import('./fanxiu/spirit-beast-hall/page.vue'),
  },
  {
    routeName: 'FanxiuMagicTreasureHall',
    canonicalPath: '/fanxiu/inventory/magic-treasure-hall',
    component: () => import('./fanxiu/magic-treasure-hall/page.vue'),
  },
  {
    routeName: 'FanxiuMagicTreasureFormations',
    canonicalPath: '/fanxiu/inventory/magic-treasure-hall/formations',
    component: () => import('./fanxiu/magic-treasure-formations/page.vue'),
  },
  {
    routeName: 'FanxiuSpiritArtifactHall',
    canonicalPath: '/fanxiu/inventory/spirit-artifact-hall',
    component: () => import('./fanxiu/spirit-artifact-hall/page.vue'),
  },
  {
    routeName: 'BeastSoulCalculator',
    canonicalPath: '/fanxiu/calculator',
    component: () => import('./fanxiu/calculator/page.vue'),
  },
  {
    routeName: 'FanxiuXianqiaoMechanics',
    canonicalPath: '/fanxiu/xianqiao',
    component: () => import('./fanxiu/xianqiao/page.vue'),
  },
  {
    routeName: 'DrawCalculator',
    canonicalPath: '/fanxiu/draw-calc',
    component: () => import('./fanxiu/draw-calc/page.vue'),
  },
  {
    routeName: 'FanxiuLotteryModel',
    canonicalPath: '/fanxiu/lottery-model',
    component: () => import('./fanxiu/lottery-model/page.vue'),
  },
  {
    routeName: 'FanxiuDiscountGuide',
    canonicalPath: '/fanxiu/discount',
    component: () => import('./fanxiu/discount/page.vue'),
  },
  {
    routeName: 'FanxiuRecharge',
    canonicalPath: '/fanxiu/recharge',
    component: () => import('./fanxiu/recharge/page.vue'),
  },
  {
    routeName: 'FanxiuXianzhouMarathon',
    canonicalPath: '/fanxiu/activity-list/xianzhou-marathon',
    component: () => import('./fanxiu/xianzhou-race/page.vue'),
  },
  {
    routeName: 'CuijianTrial',
    canonicalPath: '/fanxiu/cuijian-trial',
    component: () => import('./fanxiu/cuijian-trial/page.vue'),
  },
  {
    routeName: 'DspCalculator',
    canonicalPath: '/dsp/calculator',
    component: () => import('./dsp/calculator/page.vue'),
  },
  {
    routeName: 'MystiaWiki',
    canonicalPath: '/mystia/wiki',
    component: () => import('./mystia/wiki/page.vue'),
  },
  {
    routeName: 'VolcanoPrincessAudioCatalog',
    canonicalPath: '/volcano-princess/audio',
    component: () => import('./volcano-princess/audio/page.vue'),
  },
  {
    routeName: 'VolcanoPrincessTheaterCatalog',
    canonicalPath: '/volcano-princess/theater',
    component: () => import('./volcano-princess/theater/page.vue'),
  },
  {
    routeName: 'ZaohuaAlchemyCatalog',
    canonicalPath: '/zaohua/alchemy',
    component: () => import('./zaohua/alchemy/page.vue'),
  },
  {
    routeName: 'ZaohuaFurnaceCatalog',
    canonicalPath: '/zaohua/furnaces',
    component: () => import('./zaohua/furnaces/page.vue'),
  },
  {
    routeName: 'ZaohuaHerbCatalog',
    canonicalPath: '/zaohua/herbs',
    component: () => import('./zaohua/herbs/page.vue'),
  },
  {
    routeName: 'ZaohuaPasturePlanner',
    canonicalPath: '/zaohua/pasture',
    component: () => import('./zaohua/pasture/page.vue'),
  },
  {
    routeName: 'GuigubahuangGuide',
    canonicalPath: '/guigubahuang/guide',
    component: () => import('./guigubahuang/guide/page.vue'),
  },
  {
    routeName: 'FanxiuGongfaAtlas',
    canonicalPath: '/fanxiu/inventory/gongfa-atlas',
    component: () => import('./fanxiu/gongfa-atlas/page.vue'),
  },
  {
    routeName: 'ZaohuaGradeReference',
    canonicalPath: '/zaohua/grades',
    component: () => import('./zaohua/grades/page.vue'),
  },
  {
    routeName: 'PokemonTcgCatalog',
    canonicalPath: '/pokemon-tcg/catalog',
    component: () => import('./pokemon-tcg/page.vue'),
  },
  {
    routeName: 'XorMatrix',
    canonicalPath: '/magic-craft/xor-matrix',
    component: () => import('./magic-craft/xor-matrix/page.vue'),
  },
  {
    routeName: 'NotesCenter',
    canonicalPath: '/notes/center',
    component: () => import('./notes/center/page.vue'),
    menuPath: '/notes/star-map',
  },
  {
    routeName: 'NotesChatData',
    canonicalPath: '/notes/chat-data',
    component: () => import('./notes/chat-data/page.vue'),
    permissionKey: 'notes.chat-data',
  },
  {
    routeName: 'NotesGithubProjects',
    canonicalPath: '/notes/github-projects',
    component: () => import('./notes/github-projects/page.vue'),
    permissionKey: 'notes.github-projects',
    requiresAuth: true,
  },
  {
    routeName: 'NotesPreparation',
    canonicalPath: '/notes/preparation',
    component: () => import('./notes/preparation/page.vue'),
    permissionKey: 'notes.preparation',
    requiresAuth: true,
  },
  {
    routeName: 'Eastmoney',
    canonicalPath: '/notes/eastmoney',
    component: () => import('./notes/eastmoney/redirect.vue'),
    permissionKey: 'notes.eastmoney',
    requiresAuth: true,
  },
  {
    routeName: 'EastmoneyTrade',
    canonicalPath: '/notes/eastmoney/trade',
    component: () => import('./notes/eastmoney/trade/page.vue'),
    permissionKey: 'notes.eastmoney',
    requiresAuth: true,
  },
  {
    routeName: 'EastmoneyHistory',
    canonicalPath: '/notes/eastmoney/history',
    component: () => import('./notes/eastmoney/history/page.vue'),
    permissionKey: 'notes.eastmoney',
    requiresAuth: true,
  },
  {
    routeName: 'EastmoneyCalculator',
    canonicalPath: '/notes/eastmoney/calculator',
    component: () => import('./notes/eastmoney/calculator/page.vue'),
    permissionKey: 'notes.eastmoney',
    requiresAuth: true,
  },
  {
    routeName: 'EastmoneyRobotHistory',
    canonicalPath: '/notes/eastmoney/robot-history',
    component: () => import('./notes/eastmoney/redirect.vue'),
    permissionKey: 'notes.eastmoney',
    requiresAuth: true,
    menuPath: null,
  },
  {
    routeName: 'EastmoneySync',
    canonicalPath: '/notes/eastmoney/sync',
    component: () => import('./notes/eastmoney/page.vue'),
    permissionKey: 'notes.eastmoney',
    requiresAuth: true,
    menuPath: null,
  },
  {
    routeName: 'Freebill',
    canonicalPath: '/notes/freebill',
    component: () => import('./notes/freebill/page.vue'),
    permissionKey: 'notes.freebill',
    requiresAuth: true,
  },
  {
    routeName: 'NotesDigitalFootprint',
    canonicalPath: '/notes/digital-footprint',
    component: () => import('./notes/digital-footprint/page.vue'),
    permissionKey: 'notes.digital-footprint',
    requiresAuth: true,
  },
  {
    routeName: 'NotesSheetManager',
    canonicalPath: '/notes/sheets',
    component: () => import('./notes/sheets-manager/page.vue'),
    permissionKey: 'notes.sheets',
    requiresAuth: true,
  },
  {
    routeName: 'PdfDocumentLibrary',
    supportsContentOnly: true,
    canonicalPath: '/notes/library',
    component: () => import('./pdf/library/page.vue'),
    permissionKey: 'notes.pdfs',
    requiresAuth: true,
  },
  {
    routeName: 'NotesTrash',
    canonicalPath: '/notes/trash',
    component: () => import('./notes/trash/page.vue'),
    permissionKey: 'notes.center',
    menuPath: null,
  },
  {
    routeName: 'NotesWechat',
    canonicalPath: '/notes/wechat-data',
    component: () => import('./notes/wechat/page.vue'),
    permissionKey: 'notes.wechat',
    requiresAuth: true,
  },
  {
    routeName: 'NotesQq',
    canonicalPath: '/notes/qq-data',
    component: () => import('./notes/wechat/page.vue'),
    permissionKey: 'notes.qq',
    requiresAuth: true,
  },
  {
    routeName: 'NotesWechatStorage',
    canonicalPath: '/notes/wechat-data/storage',
    component: () => import('./notes/wechat/storage/page.vue'),
    permissionKey: 'notes.wechat.storage',
    requiresAuth: true,
  },
  {
    routeName: 'NotesMobileSms',
    canonicalPath: '/notes/mobile-sms',
    component: () => import('./notes/mobile-sms/page.vue'),
    permissionKey: 'notes.mobile-sms',
    requiresAuth: true,
  },
  {
    routeName: 'NotesWorkbookView',
    canonicalPath: '/notes/workbooks/:workbookId',
    component: () => import('./notes/workbook-view/page.vue'),
    permissionKey: 'notes.sheets',
    requiresAuth: true,
    menuPath: null,
  },
  {
    routeName: 'NotesSheetEditor',
    canonicalPath: '/notes/sheets/:sheetId',
    component: () => import('./notes/sheet-editor/page.vue'),
    permissionKey: 'notes.sheets',
    requiresAuth: true,
    menuPath: null,
  },
  {
    routeName: 'RuntimeManagement',
    canonicalPath: '/cluster/runtime',
    component: () => import('./cluster/tasks/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'ClusterRimeContextPrediction',
    canonicalPath: '/cluster/rime-context',
    component: () => import('./cluster/rime-context/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'ClusterServices',
    canonicalPath: '/cluster/services',
    component: () => import('./cluster/services/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'HardwareTemperature',
    canonicalPath: '/cluster/hardware-temperature',
    component: () => import('./cluster/hardware-temperature/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'DeviceFileBrowser',
    canonicalPath: '/cluster/files',
    component: () => import('./cluster/files/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'ClusterTreeSize',
    canonicalPath: '/cluster/treesize',
    component: () => import('./cluster/storage/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'ClusterCodexSessions',
    canonicalPath: '/cluster/codex',
    component: () => import('./cluster/codex/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'ClusterCodexWorkbench',
    canonicalPath: '/cluster/codex/workbench',
    component: () => import('./cluster/codex/workbench.vue'),
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    routeName: 'ClusterWindowControl',
    canonicalPath: '/cluster/window-control',
    component: () => import('@/components/window-projection/WindowProjectionWorkspace.vue'),
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    routeName: 'ClusterViewChanCourse',
    canonicalPath: '/cluster/view-chan-course',
    component: () => import('./cluster/view-chan-course/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'DeviceLabelmeBrowser',
    canonicalPath: '/cluster/labelme',
    component: () => import('./cluster/labelme/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'TaskLogs',
    canonicalPath: '/cluster/logs/:id',
    component: () => import('./cluster/logs/page.vue'),
    requiresAuth: true,
    permissionKey: 'cluster.tasks',
    menuPath: '/cluster/runtime',
  },
  {
    routeName: 'PasswordGenerator',
    canonicalPath: '/tools/password-generator',
    component: () => import('./tools/password-generator/page.vue'),
  },
  {
    routeName: 'ColorTools',
    canonicalPath: '/tools/color-tools',
    component: () => import('./tools/color-tools/page.vue'),
  },
  {
    routeName: 'ImageBrowser',
    canonicalPath: '/tools/image-browser',
    component: () => import('./tools/image-browser/page.vue'),
  },
  {
    routeName: 'MusicTools',
    canonicalPath: '/tools/music-tools',
    component: () => import('./tools/music-tools/page.vue'),
  },
  {
    routeName: 'OpenScoreStudy',
    canonicalPath: '/tools/open-score-study',
    component: () => import('./tools/open-score-study/page.vue'),
  },
  {
    routeName: 'WebOutline',
    canonicalPath: '/tools/web-outline',
    component: () => import('./tools/web-outline/page.vue'),
  },
  {
    routeName: 'Units',
    canonicalPath: '/tools/units',
    component: () => import('./tools/units/page.vue'),
  },
  {
    routeName: 'Globe',
    canonicalPath: '/tools/globe',
    component: () => import('./tools/globe/page.vue'),
  },
  {
    routeName: 'BodyMap',
    canonicalPath: '/tools/body-map',
    component: () => import('./tools/body-map/page.vue'),
    permissionKey: 'tools.body-map',
    supportsContentOnly: true,
  },
  {
    routeName: 'AiConfig',
    canonicalPath: '/tools/ai-config',
    component: () => import('./tools/ai-config/page.vue'),
  },
  {
    routeName: 'AiPortal',
    canonicalPath: '/tools/ai-portal',
    component: () => import('./tools/ai-portal/page.vue'),
  },
  {
    routeName: 'ResetCodex',
    canonicalPath: '/tools/reset-codex',
    component: () => import('./tools/reset-codex/page.vue'),
  },
  {
    routeName: 'AiChat',
    canonicalPath: '/tools/ai-chat',
    component: () => import('./tools/ai-chat/page.vue'),
  },
  {
    routeName: 'AiReduction',
    canonicalPath: '/tools/ai-reduction',
    component: () => import('./tools/ai-reduction/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'AiGitCommit',
    canonicalPath: '/tools/ai-git-commit',
    component: () => import('./tools/ai-git-commit/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'AiWechat',
    canonicalPath: '/tools/ai-wechat',
    component: () => import('./tools/ai-wechat/page.vue'),
  },
  {
    routeName: 'AttendanceConfigs',
    canonicalPath: '/kq5034/configs',
    component: () => import('./attendance/configs/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'AttendanceWjxCollect',
    canonicalPath: '/kq5034/questionnaire/collect',
    component: () => import('./attendance/questionnaire/collect/page.vue'),
    permissionKey: 'attendance.wjx-feedback',
  },
  {
    routeName: 'AttendanceWjxData',
    canonicalPath: '/kq5034/questionnaire/data',
    component: () => import('./attendance/questionnaire/data/page.vue'),
    requiresAuth: true,
    permissionKey: 'attendance.wjx-data',
  },
  {
    routeName: 'AttendanceOrders',
    canonicalPath: '/kq5034/orders',
    component: () => import('./attendance/orders/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'AccountManager',
    canonicalPath: '/system/accounts',
    component: () => import('./admin/accounts/page.vue'),
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    routeName: 'MyAccount',
    canonicalPath: '/system/my-account',
    component: () => import('./admin/my-account/page.vue'),
    requiresAuth: true,
  },
  {
    routeName: 'StorageManager',
    canonicalPath: '/system/storage',
    component: () => import('./admin/images/page.vue'),
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    routeName: 'UrlCompatibility',
    canonicalPath: '/system/url-compatibility',
    component: () => import('./admin/url-compatibility/page.vue'),
    requiresAuth: true,
    requiresAdmin: true,
  },
]
