/* Auto-generated supplemental color name translations. */

export const SUPPLEMENTAL_ZH_BY_EN: Record<string, string> = {
  "Absolute Zero": "绝对零",
  "Acid green": "酸性绿",
  "Aero": "航空",
  "Aero blue": "航空蓝",
  "African violet": "非洲紫罗兰",
  "Air superiority blue": "空中优势蓝色",
  "Alabaster": "雪花石膏",
  "Alice blue": "爱丽丝蓝",
  "Alizarin": "茜素",
  "Alloy orange": "合金橙",
  "Almond": "杏仁",
  "Amaranth": "苋菜",
  "Amaranth (M&P)": "苋菜 (M&P)",
  "Amaranth pink": "苋菜粉色",
  "Amaranth purple": "苋菜紫",
  "Amaranth red": "苋菜红",
  "Amazon": "亚马逊",
  "Amber": "琥珀色",
  "Amber (SAE/ECE)": "琥珀色（SAE/ECE）",
  "Amethyst": "紫水晶色",
  "Android green": "安卓绿色",
  "Antique brass": "古董黄铜",
  "Antique bronze": "古董青铜",
  "Antique fuchsia": "古董紫红色",
  "Antique ruby": "古董红宝石",
  "Antique white": "仿古白",
  "Ao (English)": "敖（英文）",
  "Apple green": "苹果绿",
  "Apricot": "杏黄",
  "Aqua": "水色",
  "Aquamarine": "碧蓝色",
  "Arctic lime": "北极石灰",
  "Army green": "军绿色",
  "Artichoke": "朝鲜蓟",
  "Arylide yellow": "芳基黄",
  "Ash gray": "灰灰色",
  "Asparagus": "芦笋",
  "Astronaut": "宇航员",
  "Atomic tangerine": "原子橘",
  "Auburn": "奥本",
  "Aureolin": "奥雷林",
  "Avocado": "鳄梨",
  "Azure": "湛蓝",
  "Azure (X11/web color)": "天蓝色（X11/网页颜色）",
  "B'dazzled blue": "B、耀眼的蓝色",
  "Baby blue": "淡蓝色",
  "Baby blue eyes": "婴儿蓝眼睛",
  "Baby pink": "淡粉色",
  "Baby powder": "婴儿爽身粉",
  "Baker-Miller pink": "贝克米勒粉红",
  "Banana Mania": "香蕉狂热",
  "Barbie Pink": "芭比粉红",
  "Barn red": "谷仓红",
  "Battleship grey": "战舰灰",
  "Beau blue": "博蓝",
  "Beaver": "海狸",
  "Beige": "米色",
  "Big dip o’ruby": "红宝石大浸",
  "Bisque": "陶坯黄",
  "Bistre": "比斯特雷",
  "Bistre brown": "比斯特棕色",
  "Bitter lemon": "苦柠檬",
  "Bitter lime": "苦石灰",
  "Bittersweet": "苦乐参半",
  "Bittersweet shimmer": "苦乐参半的微光",
  "Black": "黑色",
  "Black Shadows": "黑色阴影",
  "Black bean": "黑豆",
  "Black chocolate": "黑巧克力",
  "Black coffee": "黑咖啡",
  "Black coral": "黑珊瑚",
  "Black olive": "黑橄榄",
  "Blanched almond": "白杏仁",
  "Blast-off bronze": "升空青铜",
  "Bleu de France": "法国蓝",
  "Blizzard blue": "暴雪蓝",
  "Blond": "金发女郎",
  "Blood red": "血红色",
  "Blue": "蓝色",
  "Blue (Crayola)": "蓝色（绘儿乐）",
  "Blue (Munsell)": "蓝色（孟塞尔）",
  "Blue (NCS)": "蓝色（NCS）",
  "Blue (Pantone)": "蓝色（潘通色号）",
  "Blue (RYB)": "蓝色 (RYB)",
  "Blue (pigment)": "蓝色（颜料）",
  "Blue bell": "蓝铃",
  "Blue jeans": "蓝色牛仔裤",
  "Blue sapphire": "蓝色蓝宝石",
  "Blue yonder": "那边蓝色",
  "Blue-gray": "蓝灰色",
  "Blue-green": "蓝绿色",
  "Blue-green (color wheel)": "蓝绿色（色轮）",
  "Blue-violet": "蓝紫色",
  "Blue-violet (Crayola)": "蓝紫色（Crayola）",
  "Blue-violet (color wheel)": "蓝紫色（色轮）",
  "Bluetiful": "蓝色的",
  "Blush": "腮红",
  "Bole": "伯乐",
  "Bone": "骨",
  "Bottle green": "深绿色",
  "Brandy": "白兰地",
  "Brick red": "砖红色",
  "Bright green": "亮绿色",
  "Bright lilac": "明亮的丁香色",
  "Bright maroon": "亮栗色",
  "Bright navy blue": "明亮的海军蓝",
  "Bright yellow (Crayola)": "亮黄色（绘儿乐）",
  "Brilliant rose": "灿烂玫瑰",
  "Brink pink": "边缘粉红色",
  "British racing green": "英国赛车绿",
  "Bronze": "铜色",
  "Brown": "褐色",
  "Brown sugar": "红糖",
  "Brunswick green": "不伦瑞克绿",
  "Bud green": "芽绿",
  "Buff": "浅黄色",
  "Burgundy": "勃艮第酒红",
  "Burlywood": "伯莱伍德",
  "Burnished brown": "抛光棕色",
  "Burnt orange": "焦橙色",
  "Burnt sienna": "烧焦的赭色",
  "Burnt umber": "焦琥珀色",
  "Byzantine": "拜占庭式",
  "Byzantium": "拜占庭",
  "CG blue": "CG蓝色",
  "CG red": "CG红",
  "Cadet": "学员",
  "Cadet blue": "军校蓝色",
  "Cadet blue (Crayola)": "学员蓝（Crayola）",
  "Cadet grey": "军校灰色",
  "Cadmium green": "镉绿",
  "Cadmium orange": "镉橙",
  "Cadmium red": "镉红",
  "Cadmium yellow": "镉黄",
  "Café au lait": "欧蕾咖啡",
  "Café noir": "黑咖啡厅",
  "Cambridge blue": "剑桥蓝",
  "Camel": "驼色",
  "Cameo pink": "浮雕粉色",
  "Canary": "金丝雀",
  "Canary yellow": "金丝雀黄",
  "Candy apple red": "糖果苹果红",
  "Candy pink": "糖果粉色",
  "Capri": "卡普里岛",
  "Caput mortuum": "木乃伊棕",
  "Cardinal": "红衣主教",
  "Caribbean green": "加勒比绿",
  "Carmine": "胭脂红",
  "Carmine (M&P)": "胭脂红 (M&P)",
  "Carnation pink": "康乃馨粉色",
  "Carnelian": "红玉髓",
  "Carolina blue": "卡罗莱纳蓝",
  "Carrot orange": "胡萝卜橙",
  "Castleton green": "卡斯尔顿绿",
  "Catawba": "卡托巴",
  "Cedar Chest": "雪松箱",
  "Celadon": "青瓷绿",
  "Celadon blue": "青瓷蓝色",
  "Celadon green": "青瓷绿",
  "Celeste": "塞莱斯特",
  "Celtic blue": "凯尔特蓝",
  "Cerise": "樱桃红",
  "Cerulean": "天蓝色",
  "Cerulean (Crayola)": "蔚蓝色 (Crayola)",
  "Cerulean blue": "蔚蓝",
  "Cerulean frost": "蔚蓝霜",
  "Champagne": "香槟",
  "Champagne pink": "香槟粉色",
  "Charleston green": "查尔斯顿绿",
  "Charm pink": "魅惑粉红",
  "Chartreuse (traditional)": "黄绿色（传统）",
  "Chartreuse (web)": "黄绿色（网络）",
  "Cherry blossom pink": "樱花粉色",
  "Chestnut": "栗子",
  "Chili red": "辣椒红",
  "China pink": "中国粉红",
  "China rose": "月季",
  "Chinese red": "中国红",
  "Chinese violet": "紫罗兰",
  "Chinese yellow": "中国黄",
  "Chocolate (traditional)": "巧克力（传统）",
  "Chocolate (web)": "巧克力（网络）",
  "Chocolate Cosmos": "巧克力宇宙",
  "Chrome yellow": "铬黄",
  "Cinereous": "灰质的",
  "Cinnabar": "朱砂",
  "Cinnamon Satin": "肉桂缎",
  "Citrine": "黄水晶",
  "Citron": "香橼",
  "Claret": "红葡萄酒",
  "Cobalt blue": "钴蓝",
  "Cocoa brown": "可可棕",
  "Coffee": "咖啡色",
  "Columbia Blue": "哥伦比亚蓝",
  "Congo pink": "刚果粉红",
  "Cool grey": "冷灰色",
  "Copper": "铜",
  "Copper (Crayola)": "铜（绘儿乐）",
  "Copper penny": "铜便士",
  "Copper red": "铜红",
  "Copper rose": "铜玫瑰",
  "Coquelicot": "虞美人",
  "Coral": "珊瑚红",
  "Coral pink": "珊瑚粉色",
  "Cordovan": "马臀皮",
  "Corn": "玉米",
  "Cornell red": "康奈尔红",
  "Cornflower blue": "矢车菊蓝",
  "Cornsilk": "玉米丝色",
  "Cosmic cobalt": "宇宙钴",
  "Cosmic latte": "宇宙拿铁",
  "Cotton candy": "棉花糖",
  "Coyote brown": "土狼棕",
  "Cream": "奶油色",
  "Crimson": "绯红",
  "Crimson (UA)": "深红 (UA)",
  "Crystal": "水晶",
  "Cultured": "白烟色",
  "Cyan": "青色",
  "Cyan (process)": "青色（处理）",
  "Cyber grape": "网络葡萄",
  "Cyber yellow": "网络黄",
  "Cyclamen": "仙客来",
  "Dark blue-gray": "深蓝灰色",
  "Dark brown": "深棕色",
  "Dark byzantium": "黑暗拜占庭",
  "Dark cornflower blue": "深矢车菊蓝色",
  "Dark cyan": "深青色",
  "Dark electric blue": "深电蓝色",
  "Dark goldenrod": "暗黄花",
  "Dark green": "深绿色",
  "Dark green (X11)": "深绿色(X11)",
  "Dark jungle green": "深丛林绿",
  "Dark khaki": "深卡其色",
  "Dark lava": "深色熔岩",
  "Dark liver": "深色肝",
  "Dark liver (horses)": "深色肝脏（马）",
  "Dark magenta": "深洋红色",
  "Dark moss green": "深苔藓绿",
  "Dark olive green": "深橄榄绿",
  "Dark orange": "深橙色",
  "Dark orchid": "深色兰花",
  "Dark pastel green": "深柔和的绿色",
  "Dark purple": "深紫色",
  "Dark red": "深红色",
  "Dark salmon": "深鲑鱼色",
  "Dark sea green": "深海绿色",
  "Dark sienna": "深赭色",
  "Dark sky blue": "深天蓝色",
  "Dark slate blue": "深石板蓝",
  "Dark spring green": "深春绿色",
  "Dark turquoise": "深绿松石色",
  "Dark violet": "深紫色",
  "Dartmouth green": "达特茅斯绿",
  "Davy's grey": "戴维灰",
  "Deep Space Sparkle": "深空闪耀",
  "Deep cerise": "深樱桃色",
  "Deep champagne": "深香槟色",
  "Deep chestnut": "深栗色",
  "Deep jungle green": "深丛林绿",
  "Deep pink": "深粉色",
  "Deep saffron": "深藏红花色",
  "Deep sky blue": "深邃的天蓝色",
  "Deep taupe": "深灰褐色",
  "Denim": "牛仔布",
  "Denim blue": "牛仔蓝",
  "Desert": "沙漠",
  "Desert sand": "沙漠沙子",
  "Dim gray": "暗灰色",
  "Dodger blue": "道奇蓝",
  "Dogwood rose": "山茱萸玫瑰",
  "Drab": "土褐色",
  "Duke blue": "杜克蓝",
  "Dutch white": "荷兰白",
  "Earth yellow": "土黄色",
  "Ebony": "乌木",
  "Ecru": "本色",
  "Eerie black": "诡异的黑色",
  "Eggplant": "茄子",
  "Eggshell": "蛋壳",
  "Egyptian blue": "埃及蓝",
  "Eigengrau": "艾根格劳",
  "Electric blue": "电光蓝",
  "Electric green": "电动绿",
  "Electric indigo": "电靛蓝",
  "Electric lime": "电石灰",
  "Electric purple": "电光紫",
  "Electric violet": "电紫",
  "Emerald": "碧绿",
  "Eminence": "显赫地位",
  "English green": "英式绿",
  "English lavender": "英国薰衣草",
  "English red": "英伦红",
  "English vermillion": "英国朱红色",
  "English violet": "英国紫罗兰",
  "Erin": "艾琳",
  "Eton blue": "伊顿蓝",
  "Fallow": "休耕",
  "Falu red": "法鲁红",
  "Fandango": "凡丹戈",
  "Fandango pink": "凡丹戈粉红",
  "Fashion fuchsia": "时尚紫红色",
  "Fawn": "小鹿",
  "Feldgrau": "费尔德格劳",
  "Fern green": "蕨绿",
  "Field drab": "田野土褐色",
  "Fiery rose": "火红玫瑰",
  "Finn": "芬恩",
  "Fire engine red": "消防车红色",
  "Fire opal": "火蛋白石",
  "Firebrick": "耐火砖",
  "Flame": "火焰",
  "Flax": "亚麻",
  "Flirt": "调情",
  "Floral white": "花白",
  "Fluorescent blue": "荧光蓝",
  "Forest green (Crayola)": "森林绿（绘儿乐）",
  "Forest green (traditional)": "森林绿（传统）",
  "Forest green (web)": "森林绿（网页）",
  "French beige": "法国米色",
  "French bistre": "法国小酒馆",
  "French blue": "法国蓝",
  "French fuchsia": "法国紫红色",
  "French lilac": "法国紫丁香",
  "French lime": "法国酸橙",
  "French mauve": "法国紫红色",
  "French pink": "法国粉色",
  "French raspberry": "法国覆盆子",
  "French rose": "法国玫瑰",
  "French sky blue": "法式天蓝色",
  "French violet": "法国紫罗兰",
  "Frostbite": "冻伤",
  "Fuchsia": "品红",
  "Fuchsia (Crayola)": "紫红色（绘儿乐）",
  "Fuchsia purple": "紫红色",
  "Fuchsia rose": "紫红色玫瑰",
  "Fulvous": "黄褐色",
  "Fuzzy Wuzzy": "模糊乌兹",
  "GO green": "绿色出行",
  "Gainsboro": "庚斯博罗灰",
  "Gamboge": "藤黄",
  "Generic viridian": "通用翠绿",
  "Ghost white": "幽灵白",
  "Glaucous": "灰蓝色",
  "Glossy grape": "光泽葡萄",
  "Gold": "黄金",
  "Gold (Crayola)": "金奖（绘儿乐）",
  "Gold (metallic)": "金（金属）",
  "Gold (web) (Golden)": "黄金（网页）（金色）",
  "Gold Fusion": "黄金融合",
  "Golden brown": "金棕色",
  "Golden poppy": "金罂粟",
  "Golden yellow": "金黄色",
  "Goldenrod": "金菊色",
  "Gotham green": "哥谭绿",
  "Granite gray": "花岗岩灰",
  "Granny Smith apple": "青苹果",
  "Gray (X11 gray)": "灰色（X11灰）",
  "Gray (web)": "灰色（网络）",
  "Green": "绿色",
  "Green (Crayola)": "绿色（绘儿乐）",
  "Green (Munsell)": "绿色（孟塞尔）",
  "Green (NCS)": "绿色（NCS）",
  "Green (Pantone)": "绿色（潘通色卡）",
  "Green (RYB)": "绿色 (RYB)",
  "Green (pigment)": "绿色（颜料）",
  "Green (web)": "绿色（网页）",
  "Green Lizard": "绿蜥蜴",
  "Green Sheen": "绿色光泽",
  "Green-blue": "绿蓝色",
  "Green-blue (Crayola)": "绿蓝色（Crayola）",
  "Green-cyan": "绿青色",
  "Green-yellow": "绿黄色",
  "Green-yellow (Crayola)": "绿黄色（Crayola）",
  "Grullo": "格鲁洛",
  "Gunmetal": "炮铜色",
  "Han blue": "汉蓝",
  "Han purple": "汉紫",
  "Hansa yellow": "汉莎黄",
  "Harlequin": "丑角",
  "Harvest gold": "收获黄金",
  "Heat Wave": "热浪",
  "Heliotrope": "缬草紫",
  "Heliotrope gray": "天芥菜灰",
  "Hollywood cerise": "好莱坞樱桃色",
  "Honeydew": "蜜瓜绿",
  "Honolulu blue": "檀香山蓝",
  "Hooker's green": "胡克绿",
  "Hot magenta": "热洋红色",
  "Hot pink": "艳粉色",
  "Hunter green": "猎人绿",
  "Iceberg": "冰山",
  "Icterine": "黄黄素",
  "Illuminating emerald": "闪耀祖母绿",
  "Imperial red": "帝王红",
  "Inchworm": "尺蠖",
  "Independence": "独立",
  "India green": "印度绿",
  "Indian red": "印度红",
  "Indian yellow": "印度黄",
  "Indigo": "靛色",
  "Indigo dye": "靛蓝染料",
  "Infrared": "红外线",
  "International Klein Blue": "国际奇连蓝",
  "International orange (Golden Gate Bridge)": "国际橙（金门大桥）",
  "International orange (aerospace)": "国际橙（航空航天）",
  "International orange (engineering)": "国际橙（工程）",
  "Iris": "鸢尾花",
  "Irresistible": "无法抗拒",
  "Italian sky blue": "意大利天蓝色",
  "Ivory": "象牙色",
  "Jade": "玉",
  "Japanese carmine": "日本胭脂红",
  "Japanese violet": "日本紫罗兰",
  "Jasmine": "茉莉黄",
  "Jazzberry jam": "爵士莓果酱",
  "Jet": "喷射机",
  "Jonquil": "琼奎尔",
  "June bud": "六月芽",
  "Jungle green": "丛林绿",
  "KSU purple": "KSU紫色",
  "Kelly green": "凯莉绿",
  "Keppel": "吉宝",
  "Key lime": "酸橙",
  "Khaki (X11) (Light khaki)": "卡其色(X11)(浅卡其色)",
  "Khaki (web)": "卡其色（网状）",
  "Kobe": "神户",
  "Kobi": "科比",
  "Kobicha": "小比茶",
  "Kombu green": "昆布绿",
  "Languid lavender": "慵懒的薰衣草",
  "Lapis lazuli": "青金石",
  "Laser lemon": "激光柠檬",
  "Laurel green": "月桂绿",
  "Lava": "熔岩",
  "Lavender (floral)": "薰衣草（花香）",
  "Lavender (web)": "薰衣草（网络）",
  "Lavender blue": "薰衣草蓝",
  "Lavender blush": "薰衣草腮红",
  "Lavender gray": "薰衣草灰",
  "Lawn green": "草坪绿",
  "Lemon": "柠檬",
  "Lemon chiffon": "柠檬雪纺",
  "Lemon curry": "柠檬咖喱",
  "Lemon glacier": "柠檬冰川",
  "Lemon meringue": "柠檬酥皮",
  "Lemon yellow": "柠檬黄",
  "Lemon yellow (Crayola)": "柠檬黄（绘儿乐）",
  "Liberty": "自由",
  "Light French beige": "浅法国米色",
  "Light blue": "浅蓝色",
  "Light coral": "浅珊瑚色",
  "Light cornflower blue": "浅矢车菊蓝",
  "Light cyan": "浅青色",
  "Light goldenrod yellow": "淡黄花黄",
  "Light gray": "浅灰色",
  "Light green": "浅绿色",
  "Light orange": "浅橙色",
  "Light periwinkle": "浅长春花色",
  "Light pink": "浅粉色",
  "Light salmon": "浅鲑鱼",
  "Light sea green": "浅海绿色",
  "Light sky blue": "浅天蓝色",
  "Light slate gray": "浅石板灰色",
  "Light steel blue": "轻钢蓝",
  "Light yellow": "浅黄色",
  "Lilac": "紫丁香色",
  "Lilac Luster": "淡紫色光泽",
  "Lime (color wheel)": "石灰（色轮）",
  "Lime (web) (X11 green)": "石灰（网状）（X11 绿色）",
  "Lime green": "柠檬绿",
  "Lincoln green": "林肯绿",
  "Linen": "亚麻色",
  "Lion": "狮子",
  "Liseran purple": "利瑟兰紫",
  "Little boy blue": "小男孩蓝色",
  "Liver": "肝脏",
  "Liver (dogs)": "肝脏（狗）",
  "Liver (organ)": "肝脏（器官）",
  "Liver chestnut": "肝板栗",
  "Livid": "铁青",
  "MSU green": "密歇根州立大学绿色",
  "Macaroni and Cheese": "通心粉和奶酪",
  "Madder Lake": "茜草湖",
  "Magenta": "洋红",
  "Magenta (Crayola)": "洋红色（绘儿乐）",
  "Magenta (Pantone)": "洋红色（潘通）",
  "Magenta (dye)": "洋红色（染料）",
  "Magenta (process)": "洋红色（处理）",
  "Magenta haze": "洋红色雾霾",
  "Magic mint": "神奇薄荷",
  "Magnolia": "玉兰属",
  "Mahogany": "桃花心木",
  "Maize": "玉米",
  "Maize (Crayola)": "玉米（绘儿乐）",
  "Majorelle blue": "马若雷勒蓝",
  "Malachite": "孔雀石绿",
  "Manatee": "海牛",
  "Mandarin": "普通话",
  "Mango": "芒果",
  "Mango Tango": "芒果探戈",
  "Mantis": "螳螂",
  "Mardi Gras": "狂欢节",
  "Marigold": "万寿菊黄",
  "Maroon (Crayola)": "栗色（绘儿乐）",
  "Maroon (X11)": "栗色 (X11)",
  "Maroon (web)": "栗色（网络）",
  "Mauve": "木槿紫",
  "Mauve taupe": "紫褐色",
  "Mauvelous": "淡紫色",
  "Maximum blue": "最大蓝色",
  "Maximum blue green": "最大蓝绿色",
  "Maximum blue purple": "最大蓝紫色",
  "Maximum green": "最大绿化",
  "Maximum green yellow": "最大绿黄色",
  "Maximum purple": "最大紫色",
  "Maximum red": "最大红色",
  "Maximum red purple": "最大红紫色",
  "Maximum yellow": "最大黄色",
  "Maximum yellow red": "最大黄红",
  "May green": "五月绿",
  "Maya blue": "玛雅蓝",
  "Medium aquamarine": "中号海蓝宝石",
  "Medium blue": "中蓝色",
  "Medium candy apple red": "中号糖果苹果红",
  "Medium carmine": "中胭脂红",
  "Medium champagne": "中号香槟",
  "Medium orchid": "中兰花",
  "Medium purple": "中紫色",
  "Medium sea green": "中海绿色",
  "Medium slate blue": "中石板蓝",
  "Medium spring green": "中春绿",
  "Medium turquoise": "中绿松石色",
  "Medium violet-red": "中紫红色",
  "Mellow apricot": "醇厚的杏子",
  "Mellow yellow": "醇厚的黄色",
  "Melon": "甜瓜",
  "Metallic Seaweed": "金属海藻",
  "Metallic Sunburst": "金属旭日纹",
  "Metallic gold": "金属金",
  "Mexican pink": "墨西哥粉红",
  "Middle blue": "中蓝色",
  "Middle blue green": "中蓝绿色",
  "Middle blue purple": "中蓝紫色",
  "Middle green": "中绿色",
  "Middle green yellow": "中绿黄",
  "Middle grey": "中灰色",
  "Middle purple": "中紫色",
  "Middle red": "中红",
  "Middle red purple": "中红紫色",
  "Middle yellow": "中黄色",
  "Middle yellow red": "中黄红",
  "Midnight": "午夜",
  "Midnight blue": "午夜蓝",
  "Midnight green (eagle green)": "午夜绿（鹰绿）",
  "Mikado yellow": "天皇黄",
  "Mimi pink": "咪咪粉红",
  "Mindaro": "明达罗",
  "Ming": "明",
  "Minion yellow": "小黄人黄",
  "Mint": "薄荷绿",
  "Mint cream": "薄荷霜",
  "Mint green": "薄荷绿",
  "Misty moss": "雾蒙蒙的苔藓",
  "Misty rose": "迷雾玫瑰",
  "Mode beige": "模式米色",
  "Morning blue": "晨蓝色",
  "Moss green": "苔绿色",
  "Mountain Meadow": "山地草甸",
  "Mountbatten pink": "蒙巴顿粉红",
  "Mulberry": "桑葚",
  "Mulberry (Crayola)": "桑葚（绘儿乐）",
  "Mustard": "芥末黄",
  "Myrtle green": "香桃木绿",
  "Mystic": "神秘主义者",
  "Mystic maroon": "神秘栗色",
  "Nadeshiko pink": "抚子粉红",
  "Naples yellow": "那不勒斯黄",
  "Navajo white": "纳瓦霍白",
  "Navy blue": "海军蓝",
  "Navy blue (Crayola)": "海军蓝（绘儿乐）",
  "Neon Carrot": "霓虹胡萝卜",
  "Neon blue": "霓虹蓝",
  "Neon fuchsia": "霓虹紫红色",
  "Neon green": "霓虹绿",
  "New York pink": "纽约粉红",
  "Nickel": "镍",
  "Non-photo blue": "非照片蓝色",
  "Nyanza": "尼安萨",
  "OU Crimson red": "OU 深红色",
  "Ocean Blue": "海洋蓝",
  "Ocean green": "海洋绿",
  "Ochre": "赭色",
  "Old burgundy": "老勃艮第",
  "Old gold": "老金",
  "Old lace": "旧花边",
  "Old lavender": "老薰衣草",
  "Old mauve": "老紫红色",
  "Old rose": "老玫瑰",
  "Old silver": "老银",
  "Olive": "橄榄色",
  "Olive Drab (3)": "军绿色 (3)",
  "Olive Drab 7": "军绿色 7",
  "Olive green": "橄榄绿",
  "Olivine": "橄榄石",
  "Onyx": "玛瑙",
  "Opal": "蛋白石",
  "Opera mauve": "淡紫歌剧",
  "Orange": "橙色",
  "Orange (Crayola)": "橙色（绘儿乐）",
  "Orange (Pantone)": "橙色（潘通色卡）",
  "Orange (web)": "橙色（网状）",
  "Orange peel": "橘子皮",
  "Orange soda": "橙子苏打水",
  "Orange-red": "橙红色",
  "Orange-red (Crayola)": "橙红色（Crayola）",
  "Orange-yellow": "橙黄色",
  "Orange-yellow (Crayola)": "橙黄色（Crayola）",
  "Orchid": "兰紫",
  "Orchid (Crayola)": "兰花（绘儿乐）",
  "Orchid pink": "兰花粉红",
  "Outer space (Crayola)": "外太空（绘儿乐）",
  "Outrageous Orange": "令人发指的橙色",
  "Oxblood": "牛血",
  "Oxford blue": "牛津蓝",
  "Pacific blue": "太平洋蓝",
  "Pakistan green": "巴基斯坦绿",
  "Palatinate purple": "普法尔茨紫色",
  "Pale Dogwood": "淡山茱萸",
  "Pale aqua": "淡水绿色",
  "Pale cerulean": "淡蓝色",
  "Pale pink": "淡粉色",
  "Pale purple (Pantone)": "淡紫色（潘通色）",
  "Pale silver": "淡银色",
  "Pale spring bud": "苍白的春芽",
  "Pansy purple": "三色堇紫",
  "Paolo Veronese green": "保罗·委罗内塞绿色",
  "Papaya whip": "木瓜鞭",
  "Paradise pink": "天堂粉红",
  "Parchment": "羊皮纸",
  "Paris Green": "巴黎绿",
  "Pastel pink": "淡粉色",
  "Patriarch": "宗主教",
  "Payne's grey": "佩恩的灰色",
  "Peach": "桃色",
  "Peach (Crayola)": "桃子（绘儿乐）",
  "Peach puff": "桃子泡芙",
  "Pear": "梨",
  "Pearly purple": "珠光紫",
  "Periwinkle": "长春花色",
  "Periwinkle (Crayola)": "长春花（绘儿乐）",
  "Permanent Geranium Lake": "永久天竺葵湖",
  "Persian blue": "波斯蓝",
  "Persian green": "波斯绿",
  "Persian indigo": "波斯靛蓝",
  "Persian orange": "波斯橙",
  "Persian pink": "波斯粉色",
  "Persian plum": "波斯李子",
  "Persian red": "波斯红",
  "Persian rose": "波斯玫瑰",
  "Persimmon": "柿子橙",
  "Pewter Blue": "锡蓝色",
  "Phlox": "福禄考",
  "Phthalo blue": "酞菁蓝",
  "Phthalo green": "酞菁绿",
  "Picotee blue": "皮科提蓝",
  "Pictorial carmine": "画报胭脂红",
  "Piggy pink": "小猪粉色",
  "Pine green": "松绿色",
  "Pine tree": "松树",
  "Pink": "粉红",
  "Pink (Pantone)": "粉色（潘通色号）",
  "Pink Sherbet": "粉红果子露",
  "Pink flamingo": "粉红火烈鸟",
  "Pink lace": "粉色蕾丝",
  "Pink lavender": "粉色薰衣草",
  "Pistachio": "开心果",
  "Platinum": "白金",
  "Plum": "梅红色",
  "Plum (web)": "梅花（网）",
  "Plump Purple": "丰满的紫色",
  "Polished Pine": "抛光松木",
  "Pomp and Power": "盛况与权力",
  "Popstar": "流行歌星",
  "Portland Orange": "波特兰橙",
  "Powder blue": "粉蓝色",
  "Princeton orange": "普林斯顿橙",
  "Process yellow": "工艺黄",
  "Prune": "西梅",
  "Prussian blue": "普鲁士蓝",
  "Psychedelic purple": "迷幻紫",
  "Puce": "深褐色",
  "Pullman Brown (UPS Brown)": "普尔曼布朗 (UPS 布朗)",
  "Pumpkin": "南瓜",
  "Purple": "紫色",
  "Purple (Munsell)": "紫色（孟塞尔）",
  "Purple (X11)": "紫色 (X11)",
  "Purple (web)": "紫色（网状）",
  "Purple Plum": "紫梅",
  "Purple mountain majesty": "紫金山雄伟",
  "Purple navy": "紫色海军蓝",
  "Purple pizzazz": "紫色活力",
  "Purpureus": "紫花属",
  "Queen blue": "皇后蓝",
  "Queen pink": "皇后粉红",
  "Quick Silver": "快银",
  "Quinacridone magenta": "喹吖啶酮品红色",
  "Radical Red": "激进红",
  "Raisin black": "葡萄干黑",
  "Rajah": "拉贾",
  "Raspberry": "覆盆子",
  "Raspberry glace": "覆盆子糖霜",
  "Raspberry rose": "覆盆子玫瑰",
  "Raw sienna": "生赭石",
  "Raw umber": "原琥珀色",
  "Razzle dazzle rose": "炫彩玫瑰",
  "Razzmatazz": "狂欢",
  "Razzmic Berry": "疯狂浆果",
  "Rebecca Purple": "丽贝卡·紫",
  "Red": "红色",
  "Red (Crayola)": "红色（绘儿乐）",
  "Red (Munsell)": "红色（孟塞尔）",
  "Red (NCS)": "红色（NCS）",
  "Red (Pantone)": "红色（潘通）",
  "Red (RYB)": "红色 (RYB)",
  "Red (pigment)": "红色（颜料）",
  "Red Salsa": "红莎莎酱",
  "Red-orange": "红橙色",
  "Red-orange (Color wheel)": "红橙色（色轮）",
  "Red-orange (Crayola)": "红橙色（Crayola）",
  "Red-purple": "红紫色",
  "Red-violet": "红紫色",
  "Red-violet (Color wheel)": "红紫色（色轮）",
  "Red-violet (Crayola)": "红紫色 (Crayola)",
  "Redwood": "红木",
  "Resolution blue": "分辨率蓝色",
  "Rhythm": "节奏",
  "Rich black": "浓郁的黑色",
  "Rich black (FOGRA29)": "浓郁的黑色 (FOGRA29)",
  "Rifle green": "步枪绿",
  "Robin egg blue": "知更鸟蛋蓝色",
  "Rocket metallic": "火箭金属",
  "Rojo Spanish red": "罗霍西班牙红",
  "Roman silver": "罗马银",
  "Rose": "玫瑰红",
  "Rose Dust": "玫瑰尘",
  "Rose Pompadour": "罗丝·蓬巴杜",
  "Rose bonbon": "玫瑰糖果",
  "Rose ebony": "玫瑰乌木",
  "Rose madder": "玫瑰茜草",
  "Rose pink": "玫瑰粉色",
  "Rose quartz": "蔷薇石英",
  "Rose red": "玫红",
  "Rose taupe": "玫瑰灰褐色",
  "Rose vale": "玫瑰谷",
  "Rosewood": "玫瑰木",
  "Rosso corsa": "红红",
  "Rosy brown": "玫瑰棕",
  "Royal blue (dark)": "宝蓝色（深色）",
  "Royal blue (light)": "宝蓝色（浅色）",
  "Royal purple": "皇家紫",
  "Royal yellow": "皇家黄",
  "Ruber": "鲁贝尔",
  "Rubine red": "宝石红",
  "Ruby": "红宝石色",
  "Ruby red": "宝石红",
  "Rufous": "红褐色",
  "Russet": "赤褐色",
  "Russian green": "俄罗斯绿",
  "Russian violet": "俄罗斯紫罗兰",
  "Rust": "铁锈",
  "Rusty red": "锈红色",
  "Sacramento State green": "萨克拉门托州绿",
  "Saddle brown": "马鞍棕",
  "Safety orange": "安全橙",
  "Safety orange (blaze orange)": "安全橙（火焰橙）",
  "Safety yellow": "安全黄",
  "Saffron": "藏红花",
  "Sage": "鼠尾草",
  "Salmon": "鲑红",
  "Salmon pink": "鲑鱼粉红",
  "Sand": "沙子",
  "Sand dune": "沙丘",
  "Sandy brown": "沙棕色",
  "Sap green": "暗绿色",
  "Sapphire": "蓝宝石色",
  "Sapphire (Crayola)": "蓝宝石（绘儿乐）",
  "Sapphire blue": "宝石蓝",
  "Satin sheen gold": "缎面光泽金色",
  "Scarlet": "腥红",
  "Schauss pink": "绍斯粉红",
  "School bus yellow": "校车黄色",
  "Screamin' Green": "尖叫绿",
  "Sea green": "海绿色",
  "Sea green (Crayola)": "海绿（绘儿乐）",
  "Seal brown": "海豹棕色",
  "Seance": "降神会",
  "Seashell": "海贝色",
  "Selective yellow": "选择性黄色",
  "Sepia": "乌贼墨色",
  "Shadow": "影子",
  "Shadow blue": "暗影蓝",
  "Shamrock green": "三叶草绿",
  "Sheen green": "光泽绿色",
  "Shimmering Blush": "闪亮腮红",
  "Shiny Shamrock": "闪亮三叶草",
  "Shocking pink": "震撼粉色",
  "Shocking pink (Crayola)": "震撼粉色（Crayola）",
  "Sienna": "赭黄",
  "Silver": "银色",
  "Silver (Crayola)": "银（绘儿乐）",
  "Silver (Metallic)": "银（金属）",
  "Silver chalice": "银圣杯",
  "Silver pink": "银粉色",
  "Silver sand": "银砂",
  "Sinopia": "西诺比亚",
  "Sizzling Red": "铁板红",
  "Sizzling Sunrise": "炙热的日出",
  "Skobeloff": "斯科贝洛夫",
  "Sky blue": "天蓝色",
  "Sky blue (Crayola)": "天蓝色（绘儿乐）",
  "Sky magenta": "天洋红",
  "Slate blue": "石板蓝",
  "Slate gray": "板岩灰",
  "Slimy green": "粘糊糊的绿色",
  "Smitten": "迷恋",
  "Smoky black": "烟熏黑",
  "Snow": "雪色",
  "Solid pink": "纯粉色",
  "Sonic silver": "索尼克银",
  "Space cadet": "太空学员",
  "Spanish bistre": "西班牙小酒馆",
  "Spanish blue": "西班牙蓝",
  "Spanish carmine": "西班牙胭脂红",
  "Spanish gray": "西班牙灰",
  "Spanish green": "西班牙绿",
  "Spanish orange": "西班牙橙",
  "Spanish pink": "西班牙粉红",
  "Spanish red": "西班牙红",
  "Spanish sky blue": "西班牙天蓝色",
  "Spanish violet": "西班牙紫罗兰",
  "Spanish viridian": "西班牙语 viridian",
  "Spring Frost": "春霜",
  "Spring bud": "春芽",
  "Spring green": "春绿",
  "Spring green (Crayola)": "春天的绿色（绘儿乐）",
  "St. Patrick's blue": "圣帕特里克蓝",
  "Star command blue": "星令蓝",
  "Steel Teal": "钢青色",
  "Steel blue": "钢蓝色",
  "Steel pink": "钢粉色",
  "Stil de grain yellow": "仍然是颗粒黄色",
  "Straw": "稻草",
  "Strawberry": "草莓",
  "Strawberry Blonde": "草莓金发女郎",
  "Sugar Plum": "糖梅",
  "Sunglow": "阳光",
  "Sunray": "新蕾",
  "Sunset": "日落",
  "Super pink": "超粉色",
  "Sweet Brown": "甜棕",
  "Syracuse Orange": "锡拉丘兹橙",
  "Tan": "日晒色",
  "Tan (Crayola)": "谭（绘儿乐）",
  "Tangerine": "橘色",
  "Tango pink": "探戈粉红",
  "Tart Orange": "酸橙",
  "Taupe": "灰褐色",
  "Taupe gray": "灰褐色",
  "Tea green": "茶绿",
  "Tea rose": "茶玫瑰",
  "Teal": "凫绿",
  "Teal blue": "水鸭蓝色",
  "Telemagenta": "电信洋红",
  "Tenné (tawny)": "Tenne（黄褐色）",
  "Terra cotta": "兵马俑",
  "Thistle": "蓟紫",
  "Thulian pink": "苏莲粉红",
  "Tickle Me Pink": "给我挠痒痒粉色",
  "Tiffany Blue": "蒂芙尼蓝",
  "Timberwolf": "森林狼",
  "Titanium yellow": "钛黄",
  "Tomato": "蕃茄红",
  "Tourmaline": "电气石",
  "Tropical rainforest": "热带雨林",
  "True Blue": "真蓝",
  "Trypan Blue": "台盼蓝",
  "Tufts blue": "簇绒蓝色",
  "Tumbleweed": "风滚草",
  "Turquoise": "绿松石色",
  "Turquoise blue": "绿松石蓝",
  "Turquoise green": "绿松石绿",
  "Turtle green": "龟绿",
  "Tuscan": "托斯卡纳",
  "Tuscan brown": "托斯卡纳棕",
  "Tuscan red": "托斯卡纳红",
  "Tuscan tan": "托斯卡纳棕褐色",
  "Tuscany": "托斯卡纳",
  "Twilight lavender": "暮色薰衣草",
  "Tyrian purple": "泰尔紫",
  "UA blue": "UA蓝",
  "UA red": "UA红",
  "UP Forest green": "UP 森林绿",
  "UP maroon": "上栗色",
  "USAFA blue": "美国空军蓝",
  "Ultra pink": "超粉色",
  "Ultra red": "超红",
  "Ultramarine": "极浓海蓝",
  "Ultramarine blue": "群青蓝",
  "Umber": "翁贝尔",
  "Unbleached silk": "未漂白丝绸",
  "United Nations blue": "联合国蓝",
  "University of Pennsylvania red": "宾夕法尼亚大学红",
  "Unmellow yellow": "不醇黄",
  "Upsdell red": "厄普斯德尔红",
  "Uranian blue": "天王星蓝",
  "Van Dyke brown": "范戴克棕色",
  "Vanilla": "香草",
  "Vanilla ice": "香草冰",
  "Vegas gold": "维加斯黄金",
  "Venetian red": "威尼斯红",
  "Verdigris": "铜绿",
  "Vermilion": "朱红",
  "Veronica": "维罗妮卡",
  "Violet": "紫罗兰色",
  "Violet (RYB)": "紫罗兰 (RYB)",
  "Violet (color wheel)": "紫罗兰色（色轮）",
  "Violet (crayola)": "紫罗兰（绘儿乐）",
  "Violet (web)": "紫罗兰（网）",
  "Violet-blue": "紫蓝色",
  "Violet-blue (Crayola)": "紫蓝色（Crayola）",
  "Violet-red": "紫红色",
  "Violet-red(PerBang)": "紫红(PerBang)",
  "Viridian": "铬绿",
  "Viridian green": "常绿",
  "Vivid burgundy": "鲜艳的酒红色",
  "Vivid sky blue": "鲜艳的天蓝色",
  "Vivid tangerine": "鲜艳的橘子",
  "Vivid violet": "鲜艳的紫罗兰色",
  "Volt": "伏特",
  "Warm black": "暖黑",
  "Weezy Blue": "威兹蓝",
  "Wheat": "小麦色",
  "White": "白色",
  "Wild Strawberry": "野草莓",
  "Wild blue yonder": "那边狂野的蓝色",
  "Wild orchid": "野生兰花",
  "Wild watermelon": "野生西瓜",
  "Windsor tan": "温莎棕褐色",
  "Wine": "酒",
  "Wine dregs": "酒渣",
  "Winter Sky": "冬日的天空",
  "Wintergreen Dream": "冬青梦",
  "Wisteria": "紫藤色",
  "Wood brown": "木棕色",
  "Xanadu": "世外桃源",
  "Xanthic": "黄质",
  "Xanthous": "黄酮",
  "YInMn Blue": "钇锰蓝",
  "Yale Blue": "耶鲁蓝",
  "Yellow": "黄色",
  "Yellow (Crayola)": "黄色（绘儿乐）",
  "Yellow (Munsell)": "黄色（孟塞尔）",
  "Yellow (NCS)": "黄色（NCS）",
  "Yellow (Pantone)": "黄色（潘通色号）",
  "Yellow (RYB)": "黄色 (RYB)",
  "Yellow (process)": "黄色（过程）",
  "Yellow Orange": "黄橙",
  "Yellow Orange (Color Wheel)": "黄橙色（色轮）",
  "Yellow Sunshine": "黄色阳光",
  "Yellow-green": "黄绿色",
  "Yellow-green (Color Wheel)": "黄绿色（色轮）",
  "Yellow-green (Crayola)": "黄绿色（Crayola）",
  "Zaffre": "扎夫雷",
  "Zomp": "佐普"
}

export const SUPPLEMENTAL_EN_BY_ZH: Record<string, string> = {
  "GitHub删除红1": "GitHub Deletion Red 1",
  "GitHub删除红2": "GitHub Deletion Red 2",
  "GitHub删除红3": "GitHub Deletion Red 3",
  "GitHub新增绿1": "GitHub Addition Green 1",
  "GitHub新增绿2": "GitHub Addition Green 2",
  "GitHub新增绿3": "GitHub Addition Green 3",
  "GitHub提示蓝1": "GitHub Info Blue 1",
  "GitHub提示蓝2": "GitHub Info Blue 2"
}
